src/modal/modal.component.ts, src/modal/modal.stories.ts
Closes IBM/carbon-components-angular#102
Allows the developer to specify what element within a modal initial focus should go to when the modal is opened.
**Changed**
* selectorPrimaryFocus property added to the Modal which determines which element to focus.
* ngOnInit updated to find the element with the selectorPrimaryFocus selector and focus is called on it if available
Behavior after this change when the `data-modal-primary-focus` selector is placed on the primary button in the modal footer - note the focus styling on the close button in the modal footer, instead of the previous blue border on the entire modal:
=> put focus on primary focus element in modal if specified

src/button/button.directive.ts
Closes IBM/carbon-components-angular #89
Updated the button directive to bind to `bx.bx--btn` instead of just `class`. This way a consumer of the library can apply their own styles on top of the base button.
**Changed**
* Button directive class binding behavior
=> Fix button overwriting class attribute. Fixes #89

webpack.test.js
**Changed**
* `karma-webpack` config to disable type checking for tests, for faster running of test. (Wondering if it makes sense to everybody - Let me know if not!)
=> chore(test): skip type checking for tests

src/modal/alert-modal.component.ts, src/modal/modal-footer.component.ts, src/modal/modal-header.component.ts, src/modal/modal.component.ts, src/modal/modal.service.ts
Changes made: 
1. change role from main to dialog on div
2. add label for dialog role
3. remove banner and content-info per html 5 usage
4. Add any to service method for compiling. To resolve this: error TS1122: A tuple type element list cannot be empty.
Closes IBM/carbon-components-angular #114
fixes #158
Resolves the DAP violations for the modal
**Changed**
* Changes to the various attributes on the modal to comply with accessibility
=> Fix DAP issues for Modal

src/tabs/tab-headers.component.spec.ts, src/tabs/tab-headers.component.ts
Closes IBM/carbon-components-angular#201
Tab selection was only triggered by clicking on the tab title, not the entire heading area.
**Changed**
* Move `(click)="selectTab(tabref, tab, i)"` from `<a>` to `<li>` tag.
=> fix(tabs): Redefine tab selection area

CODEOWNERS, README.md
Since we don't have to configure translations by default anymore we can drop the whole app.module example
Also adds @youda97 as a code owner so I don't have to manually add him to the reviewer list 😀
=> chore(readme): remove useless app.module example

src/input/input.directive.ts, src/input/input.stories.ts, src/input/text-area.directive.ts
Add support for light style for Input component:
http://www.carbondesignsystem.com/components/text-input/code#skip-to-content
(select `field-02` to see the light design)
**Changed**
* Add @Input for light to apply light CSS to both Text Input and Text Area
Text Input:
Text Area:
=> Add light style to Input Component

src/select/select.component.ts, src/select/select.stories.ts
add styles for Select component, for issue #163 
**Changed**
* `light` and `inline` styles as per Carbon design:
http://www.carbondesignsystem.com/components/select/code
Inline:
Light:
=> Add styles for Select component

src/table/table.component.ts
Closes IBM/carbon-components-angular#280
Closes IBM/carbon-components-angular#275
Expandable rows had a colspan related to the number of rows in the table, not the number of columns.
**Changed**
* Fix issue by setting the right colspan (replaced `this.data.length` by `row.length`).
=> fix(table): Fix expandable row width issue

src/i18n/i18n.service.ts, src/i18n/i18n.spec.ts, src/utils/object.ts
closes #301 
`Object.assign` only does a shallow merge, which of course means we'd lose any untranslated keys (potentially for whole components)
=> fix(i18n): set now does a deep merge

src/ui-shell/sidenav.component.ts
This change removes wrapper element in side nav by putting `<aside>`'s semantic role to the host element, so we don't need a custom style rule here. Not sure if it makes sense to the team, just a food for thoughts.
**Changed**
* Merged `<aside>` with the host element of `<ibm-sidenav>`.
=> chore(side-nav): make the host work as <aside>

src/breadcrumb/breadcrumb-item.component.ts
Closes IBM/carbon-components-angular#394
Use the correct href when not displaying a skeleton
**Changed**
* Use the correct href when not displaying a skeleton
=> Use the correct href when not displaying a skeleton

src/dialog/dialog.component.ts
closes #399 
I can't actually find any specific justification for keeping this, and from what I can tell it's already handled elsewhere in dialog/position ... so away it goes!
=> fix(dialog): position wrong due to scroll x/y

.storybook/preview-experimental.scss, .storybook/preview.scss, package-lock.json, package.json, src/dialog/dialog.component.ts, src/dialog/dialog.directive.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/dialog/tooltip/tooltip.component.ts, src/dialog/tooltip/tooltip.directive.ts
closes #31 
includes:
- more tweaks to the preview.scss
- updates to carbon-components
- A11Y improvements and refactors to use `afterDialogViewInit`
=> fix(dialog): add afterDialogViewInit and improve A11Y

src/tiles/clickable-tile.component.ts, src/tiles/tiles.stories.ts
Closes IBM/carbon-components-angular#413
Add support for target attribute
**New**
* Clickable tile now supports the `target` attribute
=> feat(clickable-tile): Add support for target attribute

src/combobox/combobox.component.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/list/dropdown-list.component.ts
includes:
- fix(combobox): use blur event to focus input
- lets us cleanly move focus between the list and the input
- fix(dropdown-list): element iterators should operate on the displayItems
- `getNextElement` and related methods now operate on the visiable `disaplayItems` instead of the entire list. Also moves to a `ViewChildren` query instead of manually querying the DOM (!!)
- feat(AbstractDropdownView): add blur event to view spec
- adds `blur` as a requirement for the view. Implementing classes should specify what blurs they'll emit (top, bottom, end, start, whatever makes sense for the type of view)
=> Dropdown enhancements

src/dialog/overflow-menu/overflow-menu-option.component.ts
Overflow menu option component has a default title value of null which causes null to be shown as title in the browser. Changing this to empty string to get no title which is intended there.
=> Set overflow menu option title to "" instead of null

src/button/button.directive.ts
Closes IBM/carbon-components-angular#456
The doc block for `button.directive.ts` contained a typo in an HTML code block
**Changed**
* Fixed "hmtl" typo in doc block in `button.directive.ts`
=> docs: updates hmtl typo to html, addresses #456

src/modal/modal.stories.ts, src/placeholder/placeholder.service.ts
Closes IBM/carbon-components-angular#462
I see that the `DialogService` is also using `placeholderService.createComponent()` so there may be unintended consequences from my change. I'm not sure how and what to test so please bear this in mind when doing to review.
=> fix(modal): Bring new modals on top of the old ones.

src/ui-shell/hamburger.component.ts, src/ui-shell/header.component.spec.ts, src/ui-shell/header.component.ts, src/ui-shell/ui-shell.module.ts, src/ui-shell/ui-shell.stories.ts
Closes IBM/carbon-components-angular#452
Make the hamburger menu optional in `ui-shell` by passing `ibm-hamburger` component as a content child of `ibm-header`
**New**
* Added stub `ibm-hamburger` component, using the hamburger button template from `ibm-header`
* Added a few simple tests for the `ibm-header` component
**Changed**
* Updated the storyboard for `ui-shell` by adding the `ibm-hamburger` as a content child to all `ibm-header` components
* Updated the storyboard for `ui-shell` by adding a Knob to show/hide the `ibm-hamburger` component
=> Ui shell hamburger optional

scripts/deploy.sh
And ensure the latest v2 releases are published under `/v2`
=> chore: run pages deploy on the v9 branch

src/content-switcher/content-switcher-option.directive.ts
Closes IBM/carbon-components-angular#450
Fix for "if I click on one of the content switcher buttons and then click on a button separate from the content switcher, the content switcher button I selected becomes unselected" part of IBM/carbon-components-angular#450 issue
=> Fix content-switcher button being unselected

src/pagination/pagination.component.ts
Closes IBM/carbon-components-angular#546
This pull requests adds the possibility to define the options for the items per page select, they were always defined as 10, 20, 30, 40, 50, now a user can define whatever numbers they want.
**New**
* Now is possible to set the options for the items per page select on pagination
=> feat(pagination): Added possibility to define the options for the items per page select

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts
Extend the dropdown component to support rendering the current value via an angular template. This is similar to the template support the dropdown-list component already has.
**Changed**
* extend the dropdown components `displayValue` input parameter to accept a template as well as a string.
=> Support render template in dropdown component

src/pagination/pagination.component.ts
Closes IBM/carbon-components-angular#550
This pull requests adds the possibility to define the options for the items per page select, they were always defined as 10, 20, 30, 40, 50, now a user can define whatever numbers they want.
**New**
* Now is possible to set the options for the items per page select on pagination
=> V2 - feat(pagination): Added possibility to define the options for the items per page select

src/notification/notification.service.ts
Fix for issue #587 `NotificationService` does not remove references to closed notifications
**New**
**Changed**
* `NotificationService` removes references to closed notifications
**Removed**
=> Fix: NotificationService does not remove references to closed notifications

package.json
Closes IBM/carbon-components-angular#609
Remove peer dependencies that are not directly used in the production build of the project.  ...including `@angular/http`, which is deprecated and does not have a version 8 release.
**Changed**
* Removed '@angular/http' from peerDependencies
* Removed '@angular/compiler' from peerDependencies
* Removed '@angular/platform-browser' from peerDependencies
* Removed '@angular/platform-browser-dynamic' from peerDependencies
=> fix: remove unnecessary peer dependencies

src/input/label.component.ts
Closes IBM/carbon-components-angular#621
Set id attribute on element inside text input wrapper instead of wrapper itself.
=> fix(issue 621): Set id attribute on element within text input wrapper

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts
The multi-select codepaths didn't handle the `value` input _at all_, now they do 🎉 
Also added some error reporting to `propagateSelected` since there was a chance we could pass it `null`s and blow it up.
=> fix(dropdown): improve multi-select value handling

src/dialog/tooltip/tooltip-definition.component.ts, src/dialog/tooltip/tooltip-icon.component.ts
A button with no type attribute acts as type="submit", and will attempt to submit form data when clicked. Without this change, this component is useless inside an angular form as clicking the buttons will submit the form.
=> Tooltip controls buttons need type of button to work in forms

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
The primary fix here is switching control of value propagation away from
flatpickr and instead handling it ourselves. This has an additional
benefit of simplifying value handling for ngModel, reactive forms,
double binding, etc.
closes #643
=> fix(datepicker): valueChange emits on change

src/dialog/overflow-menu/overflow-menu-option.component.ts, src/modal/modal.component.ts
Closes IBM/carbon-components-angular#571
@cal-smith has a PR #674 for fixing #571 in v2. The Assess UX Redesign team has come across the same issue in v3. So I just cherry pick PR #674 (except the `package-lock.json`) and created this PR.
See PR #674 . I just cherry pick that one except the `package-lock.json` file.
When I used these changes in my local node module for Carbon Components Angular with Assess I don't see the error in the console anymore.
Before:
After:
=> fix(overflow-menu): change after checked errors

src/i18n/i18n.service.ts, src/i18n/i18n.spec.ts, src/pagination/pagination.component.ts, src/table/table.component.ts, src/table/toolbar/table-toolbar.component.ts, src/tiles/expandable-tile.component.ts, src/toggle/toggle.component.ts, src/toggle/toggle.stories.ts
Adds the notion of an "Overridable" to `I18N`. From the comments:
> Largely an internal usecase. There are situations where we want an `Observable` that can emit events from a centralized source **OR** an `Observable` that will emit events from a component local source. The key example being on/off text in a `Toggle` - In some cases we want the `Toggle` to use `I18n`s global translations, but in others we'd prefer to use a local override. We don't ever need to return to an non-overriden state, but we do need the ability to switch _to_ an overridden sate.
=> fix(i18n): allow for values to be overriden

src/tabs/tab-headers.component.ts
{{When the tab is template and the window is resized to be changed to a dropdown list; The selection will not make the tab name change}}
**New**
**Changed**
* {{Add template processing, when the tab is template}}
**Removed**
=> fix template tab display wrong

src/ui-shell/header/header-action.component.ts, src/ui-shell/header/header.component.ts, src/ui-shell/ui-shell.stories.ts
- removes the close icon (consumers can add it back with an ngIf on their end, not needed with the updated carbon styles)
- updates the header to take a route
=> fix(ui-shell): remove close icon

src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#788
Closes IBM/carbon-components-angular#815
There was an issue when you have a previously selected value on the options list passed to items input in dropdown, it wasn't showing it as selected option, now it is selecting it as expected.
**Changed**
* Added validation to just trigger write value if writtenValue actually has value.
=> fix(dropdown): validate value of writtenValue before trigger write value

src/table/table.component.ts
Closes IBM/carbon-components-angular#812
The Selected All header checkbox now checks when manually select all items on the table.
**Changed**
* Add a change to false that is needed to trigger change on selectedAllCheckbox variable.
=> fix(table): trigger selectAll now checks header checkbox as expected

src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
Closes IBM/carbon-components-angular#830
There was no way to change the type of the button used on file uploader, an input has been added so devs can set the button type using the types available (primary, secondary, etc...).
**New**
* Now is possible to set the type of button you want to use on file uploader, using `buttonType` input.
=> feature(file-uploader): Add input to set button type

src/button/button.directive.ts
Button did not initialize to primary when it is initialized without a button type. 
**New**
* Initialize button type to primary when button type is not provided.
=> fix(Button): Initialize ibmButton to primary on init

.gitignore, gulpfile.js, ng-package.json, scripts/build.sh, scripts/deploy.sh, src/file-uploader/file-uploader.component.ts, src/i18n/en.ts, src/i18n/i18n.service.ts, src/i18n/i18n.spec.ts, src/modal/modal.module.ts, src/pagination/pagination.component.ts, src/table/head/table-head.component.ts, src/table/table.component.ts, src/table/table.module.ts, tsconfig.spec.json, tslint.json
Closes IBM/carbon-components-angular#641
- `en.json` is now `en.ts` - the angular compiler doesn't package `.json` by default, and there's no reason it needs to be `.json` formatted for our purposes anyway
- fixed a bunch of circular imports
- fixed some `mkrdir` deploy errors
- renamed the `Modal` decorator to `ModalDecorator` ... we'll need to have a v4 to fully support ivy, so we can drop it then ... I don't believe there will be compat issues since the decorator _doesn't work anyway_. But definitely open to suggestions on this issue.
=> feat: add basic support for angular ivy

src/pagination/pagination.component.ts, src/pagination/pagination.module.ts
Closes #764 
The arrows are aligned in the storybook but when the pagination component is used outside of the storybook they are no longer aligned as shown below:
The arrows are now aligned when the component is used both in and out of the storybook.
**Changed**
* Changed the chevron-down-16 icon component to svg path in order to properly align the arrows.
=> fix(pagination): Align pagination select arrows

src/tiles/tile-group.component.ts
Closes #859 
When initializing the selection tile component outside of the storybook, it threw an ExpressionChangedAfterItHasBeenCheckedError. It no longer throws this error.
=> fix(tiles): prevent ExpressionChangedAfterItHasBeenCheckedError when initialized

scripts/build.sh
APF was causing issues with many existing consumers. Since v4 is right around the corner, we can roll back this change and swap everything over at once to avoid further intermediate breakages.
=> feat: disable APF

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#900
When selected is an empty array it causes an error of content of undefined, a check has been added to be sure it has the used element of the array
**Changed**
* updated expression to be sure first place of array is defined
=> fix(combobox): add check to avoid error when empty array

src/dropdown/list/dropdown-list.component.ts, src/dropdown/list/scroll-custom-event.interface.ts
Closes IBM/carbon-components-angular#398
Adds the ability to set an output to get the scroll event of the ibm-dropdown-list so that user can have the opportunity to set a handler.
**New**
* scroll output set to ibm-dropdown-list container
The event received has the next structure:
`{ atTop: boolean, atBottom: boolean, event: Scroll }`
````
<ibm-dropdown
[label]="label"
[helperText]="helperText"
[invalid]="invalid"
[invalidText]="invalidText"
[theme]="theme"
placeholder="Select"
[disabled]="disabled"
(selected)="selected($event)"
(onClose)="onClose($event)">
<ibm-dropdown-list [items]="items" (scroll)="handleScroll($event)"></ibm-dropdown-list>
</ibm-dropdown>
````
=> feature(dropdown-list): add ability to set output to emit scroll event

src/breadcrumb/breadcrumb-item.component.ts, src/breadcrumb/breadcrumb-item.interface.ts, src/breadcrumb/breadcrumb.component.spec.ts, src/breadcrumb/breadcrumb.component.ts
Closes IBM/carbon-components-angular#902
@cal-smith @zvonimirfras I need help fixing the tests please. I'm getting the error below and I cannot figure out how to fix it. I figured as much that if I revert the changes from the `breadcrumb-item.component.ts` then the tests are passing but I just cannot connect why would they fail with the small update.
```
HeadlessChrome 0.0.0 (Mac OS X 10.15.1)
Breadcrumb should create a breadcrumb with five items and 
an overflow menu in second position FAILED
Error: Expected 'a' to equal 'ibm-overflow-menu'.
```
=> Breadcrumb

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts
Closes #837 
DatePicker could not be opened when the calendar icon is clicked. A toggle has been added to open and close the DatePicker when the calendar icon is clicked.
**New**
* It is now possible to open and close the calendar when the calendar icon is clicked.
=> fix(date picker): Show DatePicker when calendar icon is clicked

src/combobox/combobox.component.ts
Added missing validation to avoid error when empty selected array in onSearch.
**New**
* Another validation to avoid error
=> fix(combobox): add validation to avoid error when empty selected array

src/dropdown/dropdown.component.ts
Clicking on the number icon did not clear all selected options in IE11.
=> fix(dropdown): Clear all selected options when number icon is clicked

src/tiles/selection-tile.component.ts
issue #880 
When a selection is made using the keyboard, the selected event on the tile-group was not being triggered. Now the selected event gets triggered as expected.
=> fix(selection tile): trigger selected event on tile-group on keyboard selection

src/datepicker/datepicker.component.ts
The following error shows up when building: 
```
dist/src/datepicker/datepicker.component.ts.DatePicker.html(25,7): : Property 'flatpickrInstance' is protected and only accessible within class 'DatePicker' and its subclasses.
```
It now builds without the error.
=> fix(date picker): access flatpickrInstance only within DatePicker class

src/datepicker/datepicker.component.ts
Closes #876 
Clicking on the flatpickr calendar causes the click event to propagate. It now stops the click propagation.
=> fix(date picker): stop click propagation when calendar is clicked

src/table/table-model.class.ts, src/table/table.component.ts
When the table model contains no data and onSelectAll is called, it gives the following console error:
```
ERROR TypeError: Cannot read property 'length' of undefined
at TableModel.push../src/table/table-model.class.ts.TableModel.selectAll (VM37 main.5f83aacd3a20d62a5fc8.bundle.js:21725)
at Table.push../src/table/table.component.ts.Table.onSelectAll (VM37 main.5f83aacd3a20d62a5fc8.bundle.js:22320)
at Object.eval [as handleEvent] (VM104 Table.ngfactory.js:107)
at handleEvent (VM36 vendors~main.5f83aacd3a20d62a5fc8.bundle.js:47008)
at callWithDebugContext (VM36 vendors~main.5f83aacd3a20d62a5fc8.bundle.js:48101)
at Object.debugHandleEvent [as handleEvent] (VM36 vendors~main.5f83aacd3a20d62a5fc8.bundle.js:47804)
at dispatchEvent (VM36 vendors~main.5f83aacd3a20d62a5fc8.bundle.js:44467)
at VM36 …
```
=> fix(table): check length of tableModel.data before select/deselect all

src/modal/modal-header.component.ts
In case that the modal contain a form the button on ibm-modal-header triggers the submit event due to missing `type="button"`on the button tag.
**Changed**
* Added `type="button"` to close button on modal header
=> fix(modal-header): Close button was triggering submit on form

src/datepicker-input/datepicker-input.component.ts, src/datepicker/carbon-flatpickr-month-select.ts, src/datepicker/datepicker.component.ts
When date picker is in range mode:
* Opening the calendar using the calendar icon will display the date which was last opened. For example, if the first input was clicked first, then clicking the second input will display the first input's date on the calendar.
* Switching focus between the inputs with tab will always display the second input's month. If at any point the second input has received focus.
* Manually changing the input and then clicking enter did not display the correct month on the calendar.
It all behaves as expected now.
**New**
* Manually update the month when input receives focus.
* Call updateCurrentMonth in the onMonthChange event hook in the month select plugin.
**Changed**
* When opening the calendar using the calendar icon, manually change the current month and …
=> fix(date picker): display correct date on calendar when focused or updated

src/table/head/table-head-checkbox.component.ts
- Prevents warning `'WARNING: sanitizing unsafe style value width: 10px; (see http://g.co/ng/security#xss).'` by bypassing security and trust the initial given style for hostStyle to be safe style value.
=> fix(table head checkbox): Bypass security for hostStyle

src/modal/modal.service.ts
When a modal is closed, the filtering logic should remove that component from `modalList` using `!==`.
**New**
**Changed**
**Removed**
=> fix(Modal): Fix incorrect filtering logic on close

src/datepicker/datepicker.component.ts
Open picker popup when calendar icon is clicked in a single-mode date picker. This fixes a recent regression caused by previous PR https://github.com/IBM/carbon-components-angular/pull/939.
**New**
**Changed**
**Removed**
=> fix(date picker): Open picker popup when calendar icon is clicked

src/ui-shell/header/header-action.component.ts
Conflicts with #981 
To follow the examples in https://www.carbondesignsystem.com/components/UI-shell-header/code, header actions no longer switch to close icon when active by default. It is still possible to achieve this by providing the header action with two icons and event binding to the selected event.
=> fix(ui-shell): remove close icon on active header action

src/table/table-container.component.ts
closes #1064
`dialogRef` was considered by the `isVisibleInContainer` as not visible in scrollable parents when it is within the table container because of the `overflow-x: auto` style. By adding `display: block` and `position: relative` it allows the `dialogRef` to be considered visible.
=> fix(table container): Add wrapper to allow elements to be visible in 'scrollable parents'

src/table/table-header-item.class.ts
in a striped table in dark theme there is an empty row added at the start of the table. That row shows as `undefined` in compare when a column is sorted. This ensures the empty row stays at the top. Also using localeCompare to compare a string
=> fix: make compare function more robust

src/button/button.directive.ts
Carbon only defines `bx--btn--danger`. `bx--btn--danger--primary` is not defined. https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/button/_button.scss
So we need to use `bx--btn--danger` for `danger--primary` so the button can render correctly.
**New**
**Changed**
**Removed**
=> fix: bx--btn--danger--primary undefined

src/ui-shell/panel/switcher-list-item.component.ts
Want to be able to add a target to underlying anchor so it can be opened in a new tab
**Changed**
* Created an optional target input for the anchor
=> feat(ui-shell): allow target to be set

src/tabs/tab-header-group.component.ts
Closes IBM/carbon-components-angular#1126
Moved the tab selection outside the ChangeDetector flow in order to avoid angular throwing an ExpressionChangedAfterItHasBeenCheckedError
**Changed**
* the tab selection performed in `ngAfterContentInit` is now encapsulated in a `setTimeout`
=> fix: TabHeaderGroup no longer throws ExpressionChangedAfterItHasBeenCheckedError

src/datepicker-input/datepicker-input.component.ts
Replace `ibm-icon-calendar16` component with `ibmIconCalendar16` directive to fix icon alignment issue.
Before:
After:
**New**
**Changed**
**Removed**
=> fix(datepicker): Change to svg ibmIconCalendar16

src/dialog/overflow-menu/overflow-menu.directive.ts
Closes #1118 
Since dialog service already opens the menu pane on enter or space we can remove the host listener in the overflow directive
=> fix(overflow-menu): prevent overflow menu pane from opening twice on enter or space

src/dialog/dialog-config.interface.ts, src/dialog/dialog.component.ts, src/dialog/dialog.directive.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/dialog/overflow-menu/overflow-menu.directive.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
Closes #1153 
- Allows for vertical and horizontal offsets to be specified through the `verticalOffset` and `horitontalOffset` inputs for the overflow menu.
- Allows for custom classes to be applied to dialog wrappers.
=> feat(dialog): add ability to specify vertical and horizontal offset in position

src/ui-shell/header/header-navigation-items.interface.ts
Closes IBM/carbon-components-angular#1165
**New**
N/A
**Changed**
fixed:
- commas in interface should be semi-colons
- supported values for `type` in `NavigationItem` should be separate values
- spaces changed to tabs as per tslint config for project
**Removed**
N/A
=> fix(ui-shell): #1165 - syntax errors for NavigationItem interface

src/tabs/tab-header-group.component.ts, src/tabs/tab-headers.component.ts, src/tabs/tabs.component.ts, src/tabs/tabs.stories.ts
Closes IBM/carbon-components-angular#1175
Tabs component will now accept a type property that can assume "default" or "container" value. If "container" is passed, the tabs will render accordingly with carbon styles.
**Changed**
* `ibm-tabs` and `ibm-tab-header-group` will now support `type` property
=> fix: ibm-tabs now support type container

src/input/label.component.ts
Closes IBM/carbon-components-angular#1173
Added correct wapper class for `ibm-label` when an `ibmTextArea` is passed as child
**Changed**
* `ibm-label` will now have `bx--text-input__field-wrapper` class or `bx--text-area__wrapper` one depending on its child component
=> fix: added correct wapper class for textAreas

src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#1182
Subscribe observable when set in dropdown-list component so that it doesn't rely on parent component or other events to update the values.
**Changed**
* Subscribe items observable when it's set
=> fix: subscribe observable when set in dropdown-list

package.json, src/accordion/accordion-item.component.ts, src/accordion/accordion.stories.ts
Closes IBM/carbon-components-angular#1180
**Changed**
* Added a `context` input to `ibm-accordion-item`, which is a object that is passed to `[ngTemplateOutletContext]`
=> refactor(accordion-item): adds context input

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1114
Deprecated `value` and introduced `itemValueKey` to replace it.
**New**
* added `itemValueKey` property to replace `value` in Dropdown component
**Changed**
* deprecated `value` property in Dropdown component
=> fix: deprecated Dropdown value and added itemValueKey to replace it

src/search/search.component.html
The search role is added to the **container element** that encompasses the items and objects that, as a whole, combine to create search functionality.
https://www.w3.org/TR/wai-aria-practices/examples/landmarks/search.html
**Removed**
* `role="search"` from `input` element
=> `search.component`: Remove `role="search"` from `input` element

package-lock.json, package.json, src/timepicker-select/timepicker-select.component.ts
Closes #1143 
Still not perfect, but it looks a lot better with the wrapper. It seems like a styling issue since the problem exists in the react implementation as well.
before:
after:
=> fix(timepicker-select): add input wrapper to prevent icon from displaying incorrectly in IE11

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
This will prevent the search results from being cleared when new items are added into the combobox after it has been initialized. Also added a storybook example for updating the selected items. @Pablodotnet
=> fix(combobox): prevent search results from being cleared when new items are added

src/i18n/en.ts, src/i18n/i18n.service.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
Closes IBM/carbon-components-angular#1186
Improve batch text handling to properly handle single/multiple items and also translations.
Example:
=> fix(table-toolbar): Improve batch text handling

src/modal/modal.component.ts
Closes IBM/carbon-components-angular#1220
Adding an in-line if to prevent accessing `nativeContent` of `undefined`
=> fix: prevent ibm-modal to throw errors if hasScrollingContent has not been set

src/checkbox/checkbox.component.ts, src/number-input/number.component.ts, src/search/search.component.ts, src/select/select.component.ts, src/timepicker/timepicker.component.ts
Closes #1201 
Also makes sure that any other component implementing `ControlValueAccessor` calls `onTouched` on focus out.
=> fix: manually call onTouched on focus out

src/datepicker-input/datepicker-input.component.ts
Closes IBM/carbon-components-angular#1238
I did not do any local tests (I did the change online without a local dev env), but checked the netlify preview and it now shows the icon as expected.
=> fix(datepicker): add missing icon in the datepicker

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1250
Avoid errors for this.view being undefined if it has yet to be initialised
=> Check view is initialised in ngOnChanges

src/list/list.directive.ts
Closes IBM/carbon-components-angular#1236
Fixes lists needing native HTML element wrappers when being used inside components like `ibm-accordion`
**Changed**
* Check that the element has a parent before trying to check the tag name of the parent
=> fix(list): check that parentElement exists before trying to manipulate properties on it

package-lock.json, package.json, src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts
`bx--list-box--expanded` class is needed to open the dropdown menu in carbon-components v10.11.2, this PR adds in that class
=> fix(dropdown): add in expanded class

src/table/table.component.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
Closes IBM/carbon-components-angular#1242
Fix data table focus/tabindex handling.
- `Table` component incorrectly sets `tabindex` to `-1` when a checkbox cell is clicked, which makes the cell unfocusable. This PR fixes that.
- For `TableToolbar` component, the buttons inside `batch-actions` and the buttons inside `toolbar-content` need to have `tabindex` set to `0` or `-1` properly depending on selection (since only one group of buttons will be shown). Otherwise the buttons may disappear when tabbing into the toolbar (!). Refer below screen shot.
Carbon React does the same thing: https://github.com/carbon-design-system/carbon/blob/db99425fc9164a8868a006e791fa7d1f116423a1/packages/react/src/components/DataTable/TableBatchActions.js#L53
**New**
**Changed** …
=> fix(data-table): Fix table focus/tabindex handling

src/select/select.component.ts
Change `@ViewChild` `static` to `true`, since the `select` component has `@Input` setters which will be called in `ngOnChanges`.
```
ERROR TypeError: Cannot read property 'nativeElement' of undefined
at Select.set value [as value] (carbon-components-angular.js:13207)
at Select.writeValue (carbon-components-angular.js:13215)
at setUpControl (forms.js:3186)
at FormGroupDirective.addControl (forms.js:7345)
at FormControlName._setUpControl (forms.js:8070)
at FormControlName.ngOnChanges (forms.js:7993)
at checkAndUpdateDirectiveInline (core.js:31906)
at checkAndUpdateNodeInline (core.js:44367)
at checkAndUpdateNode (core.js:44306)
at debugCheckAndUpdateNode (core.js:45328)
```
**New**
**Changed**
**Removed**
* {{removed …
=> fix(select): Change @ViewChild static to true

src/inline-loading/inline-loading.component.ts, src/inline-loading/inline-loading.stories.ts
Closes IBM/carbon-components-angular#1278
Streamlined component's state management to a single `state` property as opposed to the 2 flags `isActive` and `success`.
**New**
* Added a `@Input() state: InlineLoadingState` property to better handle the different states of the inline loading component.
* Added `errorText: string` for the error text styling.
**Changed**
* Changed `isActive` and `success` to derive from `state` for backward compatibility.
**Removed**
* Removed `_success` in favor of `state`
=> feature(inline-loading): Added `state` property and error state style.

src/inline-loading/inline-loading.component.ts, src/inline-loading/inline-loading.spec.ts
Added handling for the `state` property as a string, following the comment in https://github.com/IBM/carbon-components-angular/pull/1286
Added unit tests.
Closes IBM/carbon-components-angular#1278
=> feat(inline-loading): Added `state` property and error state style.

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.service.ts, src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#1276
Moved the `bx--list-box--expanded` class as HostBind of the DropdownList so that it will cover in one place both append inline and append to body cases. Also added `null` guard for boxMenu in the DropdownService to avoid console errors.
**Changed**
* `bx--list-box--expanded` is now added as HostBind of the DropdownList component
* added guard for boxMenu in DropdownService
=> fix(dropdown): moved expanded class as HostBind; added guard for boxMenu in dropdown service

src/tag/tag-filter.component.ts
Added `bx--tag__close-icon` class to `svg` element to align w/latest from Carbon: https://github.com/carbon-design-system/carbon/blob/09348e65d26e32a92dca4e60a09caff87843575d/packages/components/src/components/tag/_tag.scss#L156
The selector `bx--tag--filter>svg` is no longer present in the latest from Carbon. They opted for using a class selector on the `svg` element.
The latest docs from Carbon don't seem to reflect this change... I'm not sure if that is because the docs haven't yet been updated, but they should. For example, the tag filter section here no longer appears to be correct (unless I'm missing something): https://the-carbon-components.netlify.app/?nav=tag
I'm using:
"carbon-components": "^10.10.3",
"carbon-components-angular": "^4.1.6",
=> Tag Filter close icon requires a class selector for latest Carbon

src/search/search.component.ts
Closes #1233 
I was unable to reproduce the issue locally, this PR adds in a guard that should prevent such an error from coming up.
=> fix(table-toolbar): prevent error on search focusOut

src/dialog/dialog-config.interface.ts, src/dialog/dialog.directive.ts, src/dialog/tooltip/ellipsis-tooltip.directive.ts, src/dialog/tooltip/tooltip.stories.ts
This allows the ellipsis tooltip to generate the dialog content on hover, previously it only worked when trigger is click. Also prevents an empty tooltip from being generated when there is no overflow.
=> feat(ellipsis tooltip): refactor ellipsis tooltip and add disabled property for dialog

src/ui-shell/header/header-item.component.ts, src/ui-shell/header/header.component.spec.ts, src/ui-shell/header/header.component.ts, src/ui-shell/header/header.module.ts, src/ui-shell/ui-shell.stories.ts
This PR is to address a conversation I had with @cal-smith over on slack #carbon-ng. Per that conversation I tried using the `href` and `route` attributes to allow a user to right click and open in new tab. The primary issue we ran into with that was the active status of the link was no longer being tracked. 
TLDR; this adds a flag on the `ibm-header` and `ibm-header-item` that uses the `@angular/router` `routerLink` and `routerLinkActive` attributes on a standard `<a>` tag.
I don't know if this falls under the direction you all have for the project or if it's the desired way to implement it.
**New**
* add `useRouter` input to `ibm-header` and `ibm-header-item` that changes the template to use angular router's attributes
=> feat(header): add option to use angular router attributes instead of events

src/combobox/combobox.component.ts
This makes sure that the correct value is being propagated to the abstract dropdown view when the value is passed through ngModel, and the clear button is displayed/removed at the appropriate times. A revisit of #1203.
**Changed**
* Allow abstract dropdown view to propagate an array with an empty string in order to allow for clearing of selected items through ngModel by passing in an empty string.
* Show / remove clear button when values are set through ngModel.
=> fix(combobox): allow single and multi values to be reset through ngModel

src/modal/modal-header.component.ts
Modal close icon should be 20x20 according to Carbon design.
https://github.com/carbon-design-system/carbon/blob/6db63e027eeccc30d8531bf76d1983ae035767c3/packages/components/src/components/modal/_modal.scss#L342
**New**
**Changed**
* Change icon size to 20 and use svg directive instead of component.
**Removed**
=> fix(modal): Modal close icon should be 20x20

src/datepicker/datepicker.component.ts
Closes IBM/carbon-components-angular #1312 
Using the `onDayCreate` hook to add the class fixes dates not being disabled as they should be after the date picker is opened for a re-selection.
For future I think the existing code adding the class can be removed. I wasn't sure of the difference between `daysContainer` and `dayContainer` to be able to remove it myself. 
**New**
**Changed**
**Removed**
=> fix(datepicker): ensure bx classes are added on date picker creation

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes #1338 
This PR adds an optional second parameter to the `onSearch` function of the combobox `shouldEmitSearch` which controls the emitting of the search event. `shouldEmitSearch` only needs to be set to false when onChanges repeats the search when a new item is introduced to the combobox to prevent an infinite loop if a function bound to the `search` event introduces a new item.
=> fix(combobox): prevent search from emitting when items are replaced

src/dropdown/dropdown.component.ts
This makes it so the component behaviour matches the demo here: https://www.carbondesignsystem.com/components/dropdown/usage/#modifiers
**Changed**
* Make list box respect the light theme modifier
=> fix(dropdown): list box should respect the light modifier

src/table/head/table-head-cell.component.ts
Change `bx--table-header-label` from `span` to `div` to be consistent with Carbon design and React implementation.
https://github.com/carbon-design-system/carbon/blob/4538ba9816f15e50d56045af4c149f8d1eebd336/packages/react/src/components/DataTable/TableHeader.js#L73
Visual example:
`span` & wrapped text:
`div` & wrapped text:
**New**
**Changed**
**Removed**
=> fix(table): Change bx--table-header-label to div

src/checkbox/checkbox.component.ts
Closes IBM/carbon-components-angular#1367
This issue was introduced by https://github.com/IBM/carbon-components-angular/commit/a6bbc5f0a645fd149858213d886a2d3f1a77f965 that is generating 2 events for every state change of the checkbox. But the issue that fix was trying to address was instead generated by `id`s duplication when setting the `id` property of checkbox component. That would make both the `ibm-checkbox` element and the inner `input` element have the same `id`, but the label pointing only to the first in line (in this case the `ibm-checkbox`) so any click performed there when `id` property is set was no longer going to the `input`. With this solution i'm preventing the `id` duplication, so the label will point to the right element.
**Changed**
* Defining `id` property, the inner …
=> fix(Checkbox): not changing checked value on first click

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1371
Some css and html structure has changed in carbon-components that would break the current Dropdown implementation.
**Changed**
* Aligned css classes and html structure with carbon-components expectations
=> fix(Dropdown): fixed misalignments with latest carbon-components version

src/datepicker/datepicker.module.ts
Update datepicker I18nModule import to include index, which may solve a build issue for Angular 8 projects (so far reproduced in 3 Angular 8 projects).
`ERROR in Unexpected value 'undefined' imported by the module 'DatePickerModule in .../node_modules/carbon-components-angular/carbon-components-angular.d.ts'`
**New**
**Changed**
**Removed**
=> fix(build): Update datepicker I18nModule import

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1385
reorganized `checkForReorder` calls to include the pre-selected case and the reactive forms usecase.
**Changed**
* pre-selected values will now be re-arranged based on selectionFeedback
=> fix(Dropdown): pre-selected values will now be re-arranged based on selectionFeedback

src/notification/notification-content.interface.ts, src/notification/notification.component.spec.ts, src/notification/notification.component.ts, src/notification/notification.module.ts, src/notification/notification.stories.ts, src/notification/toast.component.ts
Closes IBM/carbon-components-angular#1240
Adds support for links in notifications as part of the `NotificationContent` interface
=> feat(notification): add support for links

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
When selected items are initialized or set with the `selected` key, clear button was not being set. This PR sets the clear selected button if any items are selected.
=> fix(combobox): set clear button on updateSelected

src/inline-loading/inline-loading.component.ts, src/inline-loading/inline-loading.module.ts, src/inline-loading/inline-loading.spec.ts, src/inline-loading/inline-loading.stories.ts
Closes IBM/carbon-components-angular#1278
Cherry picked `InlineLoadingState` from v3 to v4
=> Ported to V4 - feat(inline-loading): Added `state` property and error state style. 

src/modal/modal-header.component.ts
According to WCAG and Accessibility Checker plugin, buttons require "visible" text. Because of this, `aria-label` is insufficient... Adding the text as a child node of the button, but visually hiding it, meets all a11y requirements, and the `aria-label` is not longer necessary.
Voiceover and JAWS will read the button label when they announce the button element, using this approach.
**New**
* close button label added as "assistive text" `span` element
**Removed**
* close button `aria-label` is no longer needed.
=> 🛠 [Enhancement]: Update modal header close button a11y support

src/modal/alert-modal.component.ts, src/modal/modal.component.ts
Modal documentation contains ibm-modal-placeholder instead of correct ibm-placeholder. 
https://angular.carbondesignsystem.com/?path=/story/components-modal--documentation
**Changed**
* Change ibm-modal-placeholder to ibm-placeholder in documentation
=> fix(modal) Change ibm-modal-placeholder to ibm-placeholder in documentation

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1414
Removed unnecessary change callbacks to avoid being flagged as non pristine even if no real change happened
**Removed**
* removed unnecessary change callbacks
=> fix(ComboBox): avoid having combobox marked not pristine at startup

src/dropdown/dropdown.component.ts
Set dropdown button's type to "button" so it works nicely inside a form. Otherwise the default value is "submit". https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button.
**New**
**Changed**
**Removed**
=> fix(dropdown): Set dropdown button type

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1419
**Changed**
* now class `bx--list-box--light` gets applied to the `ibm-placeholder` as well to make the dropdown list themed light when that theme is selected
=> fix(Dropdown): fixing missing theme class when appending list to body

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1424
`onBlur` method is defined, but never used. Just registered it where needed so that the reactive from control can be marked as touched when necessary.
**Changed**
* `onBlur` is now called from some template elements
=> fix(Combobox): added missing onBlur calls in template

src/toggle/toggle.component.spec.ts, src/toggle/toggle.component.ts
Switch to new Carbon classes (`bx--toggle-input/bx--toggle__switch`) to avoid unwanted text wrapping and also improve accessibility.
According to Carbon code, the old classes are deprecated:
https://github.com/carbon-design-system/carbon/blob/6b68b558739dea743af3582eed6bdb438d53227e/packages/components/src/components/toggle/_toggle.scss#L250
React implementation: https://github.com/carbon-design-system/carbon/blob/6b68b558739dea743af3582eed6bdb438d53227e/packages/react/src/components/Toggle/Toggle.js#L108
Before:
After:
**New**
**Changed**
**Removed**
=> fix(toggle): Switch to new Carbon classes

src/content-switcher/content-switcher-option.directive.ts
PR https://github.com/IBM/carbon-components-angular/pull/1421 added event parameter to the event handlers, however, `["$event"]` wasn't added to `@HostListener()` directive (required by Angular https://angular.io/api/core/HostListener). Therefore, Angular compiler will bark like below with `fullTemplateTypeCheck` enabled:
`ERROR in src/app/product-ingredients/product-ingredients.component.html(48,19): Directive ContentSwitcherOption, Expected 1 arguments, but got 0.`
Of course the Angular error message is misleading in this case.
**New**
**Changed**
**Removed**
=> fix(content-switcher): Add missing ["$event"] parameter

src/datepicker/datepicker.component.ts
Closes https://github.com/IBM/carbon-components-angular/issues/1417
When using latest Carbon styles with Carbon Angular, the left and right arrow icons can't be displayed correctly:
This is due to the fact that some obsoleted svg styles have been removed in Carbon, see this PR: https://github.com/carbon-design-system/carbon/pull/6248/files
The React/official way is to pass the left and right arrow HTML to flatpickr:
https://github.com/carbon-design-system/carbon/blob/bf20ecda79b48d19f363b16c274a114424b0cab2/packages/react/src/components/DatePicker/DatePicker.js#L465
This PR copies the React implementation.
**New**
**Changed**
**Removed**
=> fix(datepicker): Pass left and right arrow HTML to flatpickr

src/dropdown/dropdown.component.ts
=> fix(dropdown): prevent form requirement div from being rendered if there is no invalid text

src/link/link.directive.ts, src/link/link.spec.ts, src/link/link.stories.ts
Adds the Carbon [inline link variant](https://carbondesignsystem.com/components/link/usage#inline-link) intended for links within sentences/text.
**New**
* Adds `inline` input to link directive
=> Add inline variant for links

src/tiles/expandable-tile.component.ts
Aligned html and focus elements with carbon components js structure. 
Previously there were 2 focusable elements and we only need 1
Closes https://github.com/IBM/carbon-components-angular/issues/1491
**Changed**
* Changed which elements are focusable
=> fix(tile): fix accessibility issue with expandable tile

carbon-angular-typedoc-theme/helpers/helpers.js, carbon-angular-typedoc-theme/partials/index.hbs, carbon-angular-typedoc-theme/partials/member.hbs, package-lock.json, package.json, scripts/build.sh, scripts/deploy.sh, src/link/link.directive.ts, tsconfig.json, tsconfig.spec.json, typedoc.json
I don't think we had an issue open for this, but this adds back some auto-generated documentation.
Context: When we switched to individual modules compodoc suddenly took well over half an hour to render _anything_. Obviously that wasn't sustainable. This PR switches us over to typedoc, with a basic custom theme that includes decorators where applicable, and calls out all the `@Input`s and `@Output`s in each classes Index.
typdoc also seems to be actively maintained and updated, so it's unlikely we'll need to switch again any time soon.
=> chore: switch to typedoc with a custom theme

src/combobox/combobox.component.ts
Previously itemValueKey input was added for combobox (https://github.com/IBM/carbon-components-angular/commit/33c899d3ee278137e1d9e8bd2d07b737dacdc1c9).
In that commit using of selected value for itemValueKey case wasn't added, this commit fix it.  
**Changed**
* Fix selection of element in combobox when use itemValueKey
=> fix(combobox): set selected value when use itemValueKey

src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts
Fixing error text not appearing for dropdown and combobox.
This makes error text handling the same across all components
Should fix: https://github.com/IBM/carbon-components-angular/issues/1446
**Changed**
* Class location for error text in dropdown and combobox
=> fix(error): fix error not visually appearing on dropdown and combobox

src/tabs/tab-headers.component.ts
Disabled button in tab was failing accessibility for contrast color.
Recommendation is for disabled element to have aria-disabled
fixes: https://github.com/IBM/carbon-components-angular/issues/1546
Before:
After:
=> fix(accessibility): fix accessibility violation on disabled element

src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts, src/input/label.component.ts, src/select/select.component.ts
Fix helper text location for select, input, dropdown and combobox
before:
after:
=> fix(helper): fix helper text location select, dropdown, combobox, input

src/dialog/overflow-menu/overflow-menu-pane.component.ts
Open to feedback and discussion.
I know you can pass an offset to the component but it seems wrong for the component to break by default because some parent has some position set with some modifying positions. It should work as expected by default.
Fixes: https://github.com/IBM/carbon-components-angular/issues/1557
I've even tested this with multiple nesting elements: https://codepen.io/dusanmilko/pen/pobzbqR
Before:
After:
Before:
After:
=> fix(dialog): fix dialog position or overflow menu

src/select/select.component.ts
Fixes #1536 
After select change inner value was not updated and that's why value and ngModel was not in sync and it looks like view is not updated
**Changed**
*  synchronize  inner value on select changes
=> fix(select): synchronize inner select value with ngmodel on change

src/file-uploader/file-uploader.component.ts
Closes #1570
Due to nesting wrong style is being applied to each item of file
uploader list:
`.bx--file__selected-file:last-child`
https://www.carbondesignsystem.com/components/file-uploader/style
Thanks!
=> fix(file-uploader): remove nesting for `ibm-file` items

src/ui-shell/header/header-menu.component.ts
Sometimes for custom menu it is necessary to change a header menu icon. 
For example I want to create language menu (without text, only icon). It can look like this:
To support icon changing this PR will add optional icon input for header-menu
**New**
- feat(ui-shell): Add icon input to header-menu
=> feat(ui-shell): Add icon input to header-menu

src/dialog/dialog.module.ts, src/dialog/index.ts, src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts, src/dialog/overflow-menu/overflow-menu.directive.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
Closes IBM/carbon-components-angular#1581
Adds a new component to allow rendering of custom content into an overflow menu inserted into a div rather than a ul element
**New**
* `carbon-components-angular/src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts`
**Changed**
* `carbon-components-angular/src/dialog/dialog.module.ts`
* `carbon-components-angular/src/dialog/overflow-menu/overflow-menu.diretive.ts`
* `carbon-components-angular/src/dialog/overflow-menu/overflow-menu.stories.ts`
=> 1581 - Render custom template content for an overflow menu

src/combobox/combobox.component.ts
Combobox multiselect currently closes on selection. It should stay open like how the dropdown multiselect does so user can keep making selections if needed.
This code is borrowed from dropdown logic.
Fixes: https://github.com/IBM/carbon-components-angular/issues/1584
=> fix(combobox): fix multi combobox closing on selection

src/ui-shell/header/header-action.component.ts
Missing aria label makes IBM Access Accessibility fail test
=> fix(uishell): add missing aria label on header action

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1533
Combobox (type: single) throws TypeError because of bad 
` "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))"`
**Changed**
* Added fallback value for combobox, specifically, when:
* type: single
* `itemValueKey` is falsey
=>  fix(#1533): combobox undefined typeerror

src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts, src/ui-shell/sidenav/side-nav.component.spec.ts
Closes IBM/carbon-components-angular#1611
This feature just adds an output to the `ibm-table-toolbar` so developers can execute something else at the moment they click on cancel on the toolbar when items are selected.
**New**
* `cancel` Output for `ibm-table-toolbar`
=> feat(tabletoolbar): add output for custom cancel method

src/dialog/dialog.directive.ts
Closes #1556 
`onTouchStart` is a callback that gets passed into the event service https://github.com/IBM/carbon-components-angular/blob/master/src/utils/event.service.ts which subscribes to the `touchstart` observable https://github.com/IBM/carbon-components-angular/blob/master/src/utils/event-observable.ts. Since the `touchstart` observable has passive set to true, we get the following error on chrome on mobile: `Unable to preventDefault inside passive event listener`. After removing `preventDefault` it doesn't seem to have any effect other than removing the errors that come up in the console.
=> fix(tooltip): remove preventDefault from onTouchStart

src/progress-indicator/progress-indicator.component.spec.ts, src/progress-indicator/progress-indicator.component.ts
Closes IBM/carbon-components-angular#1576
Changes updating strategy for the `current` field in the progress indicator from a setter/getter approach to updating inside of the lifecycle hook OnChanges.
**Changed**
* Updating strategy for the current field changed inside of the progress indicator
=> refactor(progress-indicator): Changes updating strategy for current field

src/dialog/tooltip/tooltip.component.ts
Same fix for tooltip as: https://github.com/IBM/carbon-components-angular/pull/1656
=>  fix(position): fix placeholder position for tooltip

src/table/table-model.class.ts
Closes IBM/carbon-components-angular#1665
`0 ==  false`, this was causing an issue with pagination that was showing the entire array length instead of the manually set length when it was set to 0
**Changed**
* `totalDataLength = 0` is no longer ignored
=> fix(table-model): fixed issue when totalDataLength is 0

src/table/cell/table-expand-button.component.ts
Expansion arrow doesn't seem to rotate on expansion. This fixes that
=> fix(table): fix table arrow not changing on expansion

src/ui-shell/sidenav/sidenav-item.component.ts
Adds a "Title" attribute to an anchor on the sidenav. 
The reason for this is for a better support on long words that might be obfuscated or links that might need a descriptive title.
=> Add title to sidenav anchor

src/icon/icon.module.ts
Import from '@carbon/icons' leads to import of all icons from this package. 
When I changed import to direct imports of icons, the size of my application vendor bundle decreased:
Dev: **-9MB**
Prod: **-6KB**
**Changed**
* Use direct import of icons in icon.module.ts
=> fix(icon): change import of icons from @carbon/icons

src/combobox/combobox.component.ts, src/dropdown/list/dropdown-list.component.ts
Follows from https://github.com/IBM/carbon-components-angular/pull/1693/files `isUpdate = true` is for updates originating from the component, `isUpdate = false` is for organic selections. This standardizes that usage, and expands the usage to `doEmitSelect` (since it wasn't handling everything like it should)
=> fix(dropdown): correct isUpdate behaviour

src/dialog/dialog.directive.ts
closes #1669
Touch and click both get registered and toggle the dialog. Touch toggles it open, click toggles it close.
Tested in chrome compatibility and safary in xcode with overflow menu.
=> fix(dialog): Remove onTouchStart

src/button/button.directive.ts, src/button/button.stories.ts
Closes #1593
I included the tooltip classes within the button directive as hostbindings for the assistive text because using the tooltip directive would place the tooltip into a placeholder component or to the body of the document. This conflicts with the html structure in https://react.carbondesignsystem.com/?path=/story/button--icon-button, unless you put the placeholder component inside the button itself which obviously isn't an option.
=> feat(button): add iconOnly option

src/index.ts
Icons modules and services must be exported the same as other modules
=> updates index.ts to export icons

src/table/table-item.class.ts
Closes https://github.com/IBM/carbon-components-angular/issues/1730
Remove `JSON.stringify` call in `TableItem.title` that broke some data tables. Return empty string if the data can’t be reasonably converted to an end user readable string. The caller can provide the title attribute in those cases.
**New**
**Changed**
**Removed**
=> fix(table): Remove JSON.stringify in TableItem.title

src/tabs/tab-header-group.component.ts, src/tabs/tab-header.component.ts, src/tabs/tab-headers.component.spec.ts, src/tabs/tab-headers.component.ts, src/tabs/tab.component.ts, src/tabs/tabs.component.spec.ts, src/tabs/tabs.module.ts
Closes #1724 
Brings the tabs up to date with react implementation. It borrows some approaches and interfaces from react implementation to match the behavior as closely as possible.
Tabs could use a bit of refactoring. Because of differences between tab headers and tab header group, it might not be reasonable to have one extend the other. It might make sense to have a tab-headers-base that contains common functionality between the two, that both extend. Not in this PR though. If we agree on this approach, I'll open an issue with this info.
=> feat(tabs): update to scrollable tabs

src/checkbox/checkbox.component.ts, src/checkbox/checkbox.stories.ts, src/table/head/table-head-checkbox.component.ts, src/table/table.component.ts
Closes #1728 
- Previously we were setting `selectAllCheckbox` to `false` if some, but not all the rows in a table were selected so `checked` in the table head checkbox is then set to `false`. When the table head checkbox is toggled again to deselect all the selected rows, `checked` is then set to `true`.
- An assumption was made in https://github.com/IBM/carbon-components-angular/blob/master/src/checkbox/checkbox.component.ts#L184 that either indeterminate is true or checked is true, but both can't be true. The indeterminate state is visual only so the actual checkbox should still either be in an unchecked or checked state. Since it's just masking the real value of the checkbox, automatically setting `checked` to false when `indeterminate` is true causes unexpected behaviors.
- The above …
=> fix(checkbox): prevent unexpected indeterminate action

src/datepicker/datepicker.component.ts
closes #1738
This empties the fields if both sides of the range aren't selected, which mimics the behavior in reference implementation.
=> fix(datepicker): range selection

src/modal/modal.component.ts
there is a bug in modals where the .bx--modal-content--overflow-indicator appears when there is no scroll on the element due to a float returned by getBoundingClientRect().height that gets rounded when clicking on the text.
**New**
since getBoundingClientRect().height returns a float, this can cause a bug when it is technically < modalContent.scrollHeight but the difference does not cause a scroll bar to appear. 
added Math.round() to the value returned by the modalContent.getBoundingClientRect().height to prevent the error when comparing against scrollHeight which returns an integer.
=> fix(modal): scroll auto detection

src/select/select.component.ts
Currently, the `select` component will always pass `value` attribute to the HTML `select`, using `""` as the default if not set by caller. This doesn't work if `""` is not the intended value. For example, consider below code:
```html
<ibm-select label="Type">
<option value="on-hand" selected="true">On hand</option>
<option value="in-transit-inbound">Inbound in-transit</option>
<option value="in-transit-outbound">Outbound in-transit</option>
</ibm-select>
```
This will be rendered as:
This happens because `""` doesn't match any option. The `select` component should only pass `value` attribute if it's set by caller.
**New**
**Changed**
**Removed**
=> fix(select): Only pass value if it's set by caller

src/checkbox/checkbox.component.ts
PR https://github.com/IBM/carbon-components-angular/pull/1337 added `<div class="bx--form-item bx--checkbox-wrapper">` container. However, it didn't remove the checkbox classes added on the host element. Therefore, we ended up with double checkbox classes:
This PR removes the checkbox classes on the host element:
Note with this fix, the `inline` input property is no longer being used anymore. Maybe we should mark that as obsoleted?
**New**
**Changed**
**Removed**
=> fix(checkbox): Avoid double checkbox classes

package-lock.json, package.json, src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/icon/icon.module.ts, src/input/input.directive.ts, src/input/input.stories.ts, src/input/label.component.ts, src/number-input/number.component.ts, src/number-input/number.stories.ts, src/select/select.component.ts, src/select/select.stories.ts
Closes IBM/carbon-components-angular#1750
Adds `warn` and `warnText` to all the form components mentioned in #1750.
=> feat(form controls): add warning state

src/input/label.component.ts
ibm-label doesn't support the use of "for" as an input, which is an accessibility violation - add it as an input rather than auto-generating it.
=> feat(label): Make labelInputId an @Input

src/dialog/dialog.directive.ts
No related issue
Fix error "TypeError: Cannot read property 'instance' of null", that appears when two or more close events occur on tooltip simultaniously and device handles them with significant delay.
**Changed**
* fix error with tooltip close events
=> fix cannot read 'instance' of null when closing tooltip on weak devices

src/icon/icon.module.ts, src/notification/notification.component.ts, src/notification/toast.component.ts
Closes IBM/carbon-components-angular#1782
Inline notification icon incorrect size
Replaced 16x16 icon in inline-notification to 20x20 to align with the specs found here https://www.carbondesignsystem.com/components/notification/style 
Before
After
=> fix(inline notification): Update status icon size

src/dropdown/dropdown.component.ts
For multi-select with ngModel, any external change that reduced the selection count to zero would be ignored.
This update solves that.
1. Open `dropdown.stories.ts`
2. Find `Multi-select with ngModel`
3. Duplicate the `<ibm-dropdown>` html, so there are *two* of them, one after the other
4. Make any change you want, and you'll see that they stay in sync -- _except_ when the change results in **no selections**.
5. For that case, the "other" dropdown ignores that update. This PR fixes this case.
> Note: This is also true for any external changes, including URL changes that might have an effect of the model, etc.
**Changed**
- `_writtenValue` is now a set/get pair, where writes with length zero call `clearSelected()`
- `clearSelected()` checks for zero case to avoid and infinite loop
=> fix(dropdown) Incoming changes on a multi select now properly accept the "zero" case

src/context-menu/context-menu-divider.component.ts, src/context-menu/context-menu-group.component.ts, src/context-menu/context-menu-item.component.ts, src/context-menu/context-menu-selection.service.ts, src/context-menu/context-menu.component.ts, src/context-menu/context-menu.module.ts, src/context-menu/context-menu.stories.ts, src/context-menu/index.ts, src/context-menu/package.json
Adds a simple context-menu implementation. [See here](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-contextmenu--context-menu) for the existing react implementation this is based on. We deviate in a few ways, and add some component level styles to make things behave, but all the functionality should be the same.
This doesn't handle displaying on right click - We can add a service later to deal with that (I'm thinking something that could serve as a proper foundation for the dialog service ... Maybe we can address some of the positioning bugs at the same time).
=> feat(context-menu): add a simple context menu component

src/search/search.component.ts
Observed an issue in Safari when using IME composition. First reported by Japanese input users and confirmed with Chinese input. Screenshots show IME input with traditional Chinese (zhuyin).
**Original on Storybook**
**Correct input**
Added a check for `isComposing` to prevent Safari from overwriting the search value with IME text, and verified with traditional Chinese in latest versions of Safari, Chrome, Edge, and Firefox.
**New**
* Adds support for IME input in Safari.
**Changed**
**Removed**
=> Add support for IME input in Safari

src/select/select.component.ts, src/select/select.stories.ts
Closes #1776
We cannot use the `value` property on select since default selected values through options tags would be ignored if a `value` is not set by the caller. #1754 addresses this but using an `attribute` means that the `attribute value` cannot change after initialization, which makes setting values through reactive forms not possible.
=> fix(select): fix reactive form functionality and allow selected to be initialized through value and options tags

src/select/select.component.ts
Closes #1776
Closes #1798 
In the storybook `@ViewChild` got the right reference to the select element but in a production build it was `undefined` so the view couldn't be programmatically updated within the component.
=> fix(select): allow view to be updated through reactive forms and ngModel in prod

src/slider/slider.component.ts
Closes IBM/carbon-components-angular#1846
I think the `IBM Equal Access Accessibility Checker` might have some issues on its own and not detecting the already existing  `for` attribute on the main `<label>` element. This PR adds a safe-guard, which feels very much a redundant labeling, by adding an `aria-labeledby` attribute on the slider handle(s)
Slider:
Range:
=> fix(slider): Fix accessibility check "1.1.1 Non-text Content: ViolationForm control with "slider" role has no associated label

src/ui-shell/header/header-navigation-items.interface.ts, src/ui-shell/header/header-navigation.component.ts, src/ui-shell/ui-shell.stories.ts
Closes IBM/carbon-components-angular#1850
Added a `UI Shell > Header fluid items to side navigation` story to demonstrate how to deal with resizing `ibm-header`.
Extended `isCurrentPage` to the `NavigationItem` interface so it can be passed as part of the `navigationItems` property.
=> refactor(ui shell): Added a fluid UI shell story

src/ui-shell/sidenav/sidenav-item.component.ts, src/ui-shell/sidenav/sidenav.component.ts, src/ui-shell/ui-shell.stories.ts
Closes IBM/carbon-components-angular#1861
* Allow `sidenav` to process the `title` property
**Changed**
* Remove `title` attribute if the `title` property is not set
=> fix(sidenav): Fixed an `undefined` tooltip always showing

src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts
Adds missing data attribute so that Carbon styles apply on the menu pane and cover the gap between the trigger and the pane itself.
=> fix(overflow-menu-pane): include floating menu direction data attribute

src/search/search.component.html, src/search/search.component.ts, src/search/search.stories.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar-search.component.ts
Closes IBM/carbon-components-angular#1856
Fixing styling issues with table-toolbar-search when using latest styling from carbon-components
**Changed**
* moved relevant classes into search component
* show toolbar classes only when search is only in toolbar mode
* moved `expandable` property into search component and applied new classes from carbon styles
* fixed issue with close on blur when focusing a focusable element (eg a button) outside the search component which wasn't closing the expandable search
=> fix(table-toolbar-search): fixing styling issue with latest carbon-components

src/number-input/number.component.ts
Adds ariaLabel as a directive for the number input component
**New**
* Number input component now can receive ariaLabel directive, which value will be passed as aria-label to the input tag.
=> fix(number-input): Setting ariaLabel as a directive for number input

README.md, integration/ng10/package-lock.json, integration/ng10/package.json, integration/ng11/package-lock.json, integration/ng11/package.json, integration/ng7/package-lock.json, integration/ng7/package.json, integration/ng8/package-lock.json, integration/ng8/package.json, integration/ng9/package-lock.json, integration/ng9/package.json, package-lock.json, package.json, src/accordion/accordion-item.component.ts, src/button/button.directive.ts, src/code-snippet/code-snippet.component.ts, src/code-snippet/code-snippet.stories.ts, src/dialog/overflow-menu/overflow-menu.stories.ts, src/dialog/tooltip/tooltip.stories.ts, src/icon/icon.module.ts, src/index.stories.ts, src/modal/modal.component.ts, src/package.json, src/patterns/dialogs/modal-with-table.stories.ts, src/table/stories/app-function-override-filter-table.component.ts, src/table/stories/app-model-filter-table.component.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts, src/ui-shell/ui-shell.stories.ts
This uses latest v11 version of @angular/cli
This is because the latest @angular/cli version is 12+ and @carbon/icons-angular complains about dependencies. It needs @angular/cli from v7 to v11.
And this fixes following the readme Getting started. Project now successfully builds.
**New**
* README - Getting started now uses angular latest v11
**Changed**
* Changed the README.md
=> Remove @carbon/icons-angular completely from this repo

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1882
If we propagate changes back to the form for all types of changes we end up setting `pristine` to `false` when there hasn't _actually_ been a valid change.
=> fix(dropdown): only propagate values for organic selections

src/file-uploader/file.component.ts
fix(file-uploader): add "tabindex=0" attribute for svg to make the close icon keyboard operable
Closes IBM/carbon-components-angular#https://github.com/IBM/carbon-components-angular/issues/1897
=> fix(file-uploader): add "tabindex=0" attribute for svg to make the close icon keyboard operable 

src/table/table-item.class.ts
Closes IBM/carbon-components-angular#1914
**Changed**
* Changed comparison to be aware of empty strings
=> fix(table): Allow setting of `title: ""` to hide the default cell tooltip

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1911
fix autocomplete attribute for native `<input>` element inside `<ibm-combo-box>` component
**New**
* add `autocomplete="off"` to `<input>`
**Changed**
* updated comments
=> 1911 combobox should disable native input autocomplete

src/index.ts
Corrected the package so ContextMenuModule can be used.
=> chore: Fix missing context-menu in index.ts, resolves #1925

src/inline-loading/inline-loading.component.ts, src/loading/loading.component.ts
Update loading icon size to be consistent with Carbon React. https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Loading/Loading.js
Before:
After:
**New**
**Changed**
**Removed**
=> fix(loading): update loading icon size

src/datepicker/datepicker.component.ts
Currently, the date picker component resets the flatpickr instance on all input changes. This is unnecessary for input changes irrelevant to flatpickr, and can cause problems in some cases esp. for range date picker. For example, if the caller updates the validation status when the user selects a start date, then the flatpickr instance will be reset (destroyed) before the user can select an end date.
This PR limits the reset to relevant input changes only.
**New**
**Changed**
**Removed**
=> fix(datepicker): reduce flatpickr reset on changes

src/radio/radio-group.component.ts
Added focuout listerner on host to mark the form control as touched
**Changed**
* Now RadioGroup correctly marks itself as touched when focus leaves the component without any change
=> Fix not touched on focus out

src/radio/radio-group.component.ts
Closes IBM/carbon-components-angular#1968
RadioGroup wasn't clearing previous radio `checked` status which was resulting in updating the wrong selection at line 237 as multiple items in the array were having `checked` set to `true`
**Changed**
* RadioGroup now clears previous `checked` status when a new radio in the group is selected
=> fix(radio-group): fix reactive form set value not always working

src/file-uploader/file-uploader.component.ts
Closes #1939 
If `multiple` is set to `false`, `removeFile` gets called due to `files` being cleared in `onFilesAdded`. This is because in the file item component, onDestroy emits remove which then calls removeFile. It does this to be able to trick the input into detecting a change when same files are uploaded after being deleted in the past through the model (files). This PR prevents removeFile from emitting filesChange if a file was removed through onFilesAdded. The component also used to emit filesChange when a file item was manually removed from files outside of the component, it no longer does that. This was inconsistent because if you manually update the files input from outside of the component in any other way (adding items) it did not emit filesChange.
=> fix(file uploader): prevent filesChange from emitting twice

src/pagination/pagination.component.ts
Add `bx--btn__icon` to caret svgs to match Carbon React. Without this fix, the left/right icons look pretty small with latest Carbon styles.
**Before:**
**After:**
**Carbon Design:**
=> fix(pagination): add bx--btn__icon to caret svgs

src/radio/radio-group.component.ts
Closes IBM/carbon-components-angular#1986
Fixed bad radio button behaviour letting the user deselect the value clicking a second time.
Also fixed initial `[checked]="true"` property on radio being overridden.
**Changed**
* fixed ability to deselect radio button (shouldn't be allowed)
=> fix(radio-group): fixed radio getting deselected on second click

src/icon/icon.directive.ts
Closes IBM/carbon-components-angular#2055
Fixed typo in IconDirective that was ignoring IconDescriptor width
**Changed**
* fixed typo to use width correctly
=> fix(IconDirective): fixed typo that was ignoring IconDescriptor width

README.md
Closes #2075
Adding the badge for the OpenSSF Best Practices Badge, for reference: https://bestpractices.coreinfrastructure.org/en/projects/5887
**New**
* added badge HTML to readme file to display on main github repo page
See image:
=> Issue 2075

src/content-switcher/content-switcher.component.ts
BugFix: White Text on Content Switcher
Upgrading Carbon on our Angular app made the white text disappear on the selected Carbon content switcher. I was told carbon-components-angular was missing <span class="bx--content-switcher__label"> and needed to be added. Please slack me on IBM's slack @jhoose if I'm incorrect as I do not check my personal gitHub account often.
jhoose-bugFixWhiteTextOnContentSwitcher
=> fix(content-switcher): White Text on Content Switcher

src/content-switcher/content-switcher-option.directive.ts, src/content-switcher/content-switcher.component.ts, src/package.json
Closes IBM/carbon-components-angular#2104
Closes IBM/carbon-components-angular#2084
Removing the span to mimic the react version of this component
**Changed**
* removed span with `bx--content-switcher__label` to fix the issue
=> fix(ContentSwitcher): correctly displaying all switcher options (and update utils-position version)

src/checkbox/checkbox.component.spec.ts, src/checkbox/checkbox.component.ts, src/checkbox/index.ts, src/forms/index.ts, src/table/cell/table-checkbox.component.ts, src/table/head/table-head-checkbox.component.ts, src/toggle/toggle.component.spec.ts, src/toggle/toggle.component.ts, src/toggle/toggle.stories.ts
Fixes toggle in v11
**New**
* Updated toggle to use new carbon styles
* Added hide label
* Template has been changed to now use a button instead of a checkbox
**Removed**
* Deprecated property bindings for checkbox
* Applied these changes in other components
=> Toggle v11

src/input/input.stories.ts, src/input/label.component.ts
Add support for disabled state to be consistent with Carbon design and React implementation.
=> fix(label): add support for disabled state

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/context-menu/context-menu-divider.component.ts, src/context-menu/context-menu-item.component.ts, src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts, src/dialog/dialog.service.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts, src/input/input.directive.ts, src/input/input.stories.ts, src/input/label.component.ts, src/modal/modal.component.ts, src/number-input/number.component.ts, src/number-input/number.stories.ts, src/search/search.component.html, src/search/search.component.spec.ts, src/search/search.component.ts, src/search/search.stories.ts, src/select/select.component.ts, src/select/select.stories.ts, src/slider/slider.component.ts, src/structured-list/list-row.component.ts, src/tiles/tile.component.ts, src/timepicker/timepicker.component.ts
**New**
- Applied conditional disable state classes to both label & helper text
**Changed**
- Added focus styling to structured list row 
- Styles are applied on focus 
- Standardize size property to `sm`, `md`, `lg` (Previously was `sm`, `md`, `xl`)
- Reflected this change in storybook & templates
**Removed**
- Deprecated input properties
- Includes updating sizes
=> Remove V4 deprecations & update label/helpertext styles for disabled state

src/search/search.component.ts
fix focus change issue when tab key press
Closes IBM/carbon-components-angular#2111
Fix issue while user go through tab key press. Set initial focus on input search when search get focus from tab key press.
**New**
* Implement focusIn HostListener method to improve tab key press event performance. 
**Before**
**After**
=> fix: fix focus change issue when tab key press

src/checkbox/checkbox.component.ts
closes #2156 
Removed the aria-checked attribute from the checkbox to conform to the accessibility directives of the IBM Accessibility Checker tool.
**Removed**
* Removed `[attr.aria-checked]` from ibm-checkbox component
=> fix: remove aria-checked from checkbox

src/modal/alert-modal.component.ts, src/modal/alert-modal.interface.ts, src/modal/base-modal.service.ts, src/modal/index.ts, src/modal/modal.component.spec.ts, src/modal/modal.component.ts, src/modal/modal.module.ts, src/modal/modal.service.ts, src/modal/modal.stories.ts, src/tsconfig.lib.json, tsconfig.json
Remove cyclic imports in modal & enable partial build in ivy. This will fix common module not found error in angular 14 @ next.
Previously:
Alert -> modal -> service -> alert
Now:
```
Alert -> Modal -> BaseService
|                      ^
|                      |
-----------------> ModalService
```
BaseService has logic for rendering modal which Modal Service extends that. Modal Service allows AlertModal to be created
=> fix(modal): Remove remote scoping to allow partial build with ivy

src/modal/modal.component.ts
`shouldShowScrollbar` uses `scrollHeight` to determine whether the modal content is scrollable or not. The problem is that `scrollHeight` returns a rounded value, and its implementation (round up or down) is browser-specific. For text elements, with the default Carbon styles, the modal content height is `28.02 px`. Different browsers may return different values. e.g.:
- Chrome seems to always return `28`.
- FireFox returns `28` for some languages (e.g. English), but returns `29` for some other languages (e.g. Chinese).
The previous implementation uses `Math.round` to round `getBoundingClientRect().height` before comparison. This results in false positive for some languages like Chinese. It seems we should use `Math.ceil` instead.
Before:
After:
=> fix(modal): fix rounding issue in shouldShowScrollbar

src/table/table.component.ts
Closes #2182 
Closes #2217 
Set focus on table header button on sorting
Fix tab focus on table header with sort button
**Changed**
* Set focus on table header button on sorting
* Fix tab focus on table header with sort button
**After**
=> fix(table): set focus on sort table header button

src/carbon.yml
This PR indexed the 4 patterns coded examples that are demoed in Storybook: https://angular.carbondesignsystem.com
**New**
* Indexed 4 patterns
**Changed**
* N/A
**Removed**
* N/A
**Testing**
Testing with:
```javascript
{
'carbon-styles': {
host: 'github.com',
org: 'mattrosno',
repo: 'carbon',
path: '/packages/styles',
maintainer: 'carbon',
group: carbonComponentsGroup,
ref: 'index-patterns'
},
'carbon-components-angular': {
host: 'github.com',
org: 'mattrosno',
repo: 'carbon-components-angular',
path: '/src',
group: carbonComponentsGroup,
ref: 'index-patterns'
}
}
```
The 4 patterns show up in the Carbon Angular assets table:
The detail page shows how this asset is Angular framework (ignore the v0.0.0... that's just from this being local indexing, also, after this next sprint, this page …
=> docs: index angular patterns

src/carbon.yml
Related: https://github.com/carbon-design-system/carbon-platform/issues/967
The Carbon Angular library has a design kits page, to list compatible design kits with the components/patterns in the Carbon Angular library: https://next.carbondesignsystem.com/libraries/carbon-components-angular/latest/design-kits
This list of `designKits` would normally be inherited from the `carbon-styles` library (PR https://github.com/carbon-design-system/carbon/pull/12033), but Carbon Angular has yet to upgrade to v11.
By not inheriting `designKits`, we can specify in this library so the v10 Figma kits are listed, not the new v11 Figma kits.
Once Carbon Angular updates to v11, we can remove the `designKits` array in the config file.
**New**
* `carbon.yml` `designKits` array of compatible design kits for …
=> docs: index compatible design kits

src/table/table.component.ts
Enable horizontal scroll in table to match Carbon React implementation.
Replaces https://github.com/IBM/carbon-components-angular/pull/2128.
=> fix(table): enable horizontal scroll in table

src/search/search.component.html, src/table/table.component.ts
Closes IBM/carbon-components-angular#2184
~Change role from `search` to `searchbox`~
~I believe `searchbox` is the correct widget role based on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#2._widget_roles~
Remove the unnecessary `tabindex`
**New**
**Changed**
* [src/search/search.component.html](https://github.com/IBM/carbon-components-angular/compare/master...makandre:carbon-components-angular:patch-2#diff-d18ddec221752adaa51aabfcf9d75769a9608dc390c37b3722eb87cb9433cbb6)
**Removed**
=> fix: Remove tabindex

src/file-uploader/file.component.ts
Closes IBM/carbon-components-angular#2233
Fix accessibility violation, the error svg icon should not be focusable.
**New**
**Changed**
* [src/file-uploader/file.component.ts](https://github.com/IBM/carbon-components-angular/compare/master...makandre:carbon-components-angular:patch-1#diff-16e04c1cd0f6cf955ab565e43d10815ef46c58f259ad86045fd9cd8c04267dff)
**Removed**
=> fix: Error svg should not have tab index

src/i18n/en.ts, src/pagination/pagination-nav/pagination-overflow.component.ts
Closes IBM/carbon-components-angular#2179
* Add `aria-label` to `select` element via i18n service
=> fix: Add associated label to 'select' element

src/toggle/toggle.component.ts
Closes IBM/carbon-components-angular#2227
* Listen for keyup enter events & execute click function to toggle state change
=> fix: Allow 'enter' key to toggle switch state

src/file-uploader/file.component.ts
Closes IBM/carbon-components-angular#2234
* Removed click/keyup events from `span` element events bubbled from `warning--filled` icon as well. This is unexpected behavior.
* Wrapped `close` icon in a `button` element.
* Made  `checkmark-filled` icon tab-able instead of it's parent (`span`).
=> fix: wrap close svg icon in a button to fix accessibility

src/button/icon-button.component.ts, src/button/icon-button.stories.ts
Prevents the same id from being assigned to the host element & the button by updating the id prop.
=> fix: prevent host & button from having same id

src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>
Closes IBM/carbon-components-angular#2213
The popup menu was missing id attribute
**New**
**Changed**
* [src/dialog/overflow-menu/overflow-menu-custom-pane.component.ts](https://github.com/IBM/carbon-components-angular/compare/master...makandre:carbon-components-angular:2213?expand=1#diff-6d4776c34026a3e7d95851bbb2ea7cbeebed7e21b9f27232385cb8913e3b23b1)
* [src/dialog/overflow-menu/overflow-menu-pane.component.ts](https://github.com/IBM/carbon-components-angular/compare/master...makandre:carbon-components-angular:2213?expand=1#diff-01e8ba07b56f1149d15573781b7708caaa7a397ac17dc98360a41e6cbb038b08)
**Removed**
=> fix: missing id on popup menu

src/table/header/table-header-description.directive.ts, src/table/header/table-header-title.directive.ts, src/table/stories/app-table.component.ts, src/table/table-container.component.ts, src/table/table.component.ts, src/table/table.stories.ts
Closes IBM/carbon-components-angular#2261
* Remove roles from Table header directives
* Add `aria-labelledby` & `aria-describedby` roles to `ibm-table`
* Update stories
=> fix: Remove incorrect roles from table header title & description

src/accordion/accordion.component.spec.ts, src/accordion/accordion.component.ts, src/accordion/accordion.stories.ts
Hello there,
I saw the open issue and thought I'd make a contribution.
It took me a while to realise, but the latest `@carbon/styles` should have the necessary styles (specifically, just the `sm` and `lg` variants) to support the changes to add the size variations to the accordion component.
As an aside, I checked out the `next` branch out of curiosity and it looks like the story for the accordion doesn't have a knob for varying the size. There's been some file movement which appears to undo the knob added previously. Not sure if this is intentional.
**New**
* Adds size variations for the accordion component
**Changed**
* N/A
**Removed**
* N/A
---
Closes IBM/carbon-components-angular#2022
=> feat(accordion): add multiple sizes (#2022)

src/carbon.yml
As found in https://github.com/carbon-design-system/carbon-platform/issues/907, added a "Get started" page to the Carbon Angular library with https://carbondesignsystem.com/developing/frameworks/angular content.
=> docs: index getting started content

src/pagination/pagination.component.ts
closes #2264
Update pagination component to fix a11y label of page selector
**New**
N/A
**Changed**
Change hidden label for page selector
**Removed**
N/A
=> fix(pagination): Use pageText instead of itemsPerPageText to fix a11y label

src/ui-shell/header/header-item.component.ts, src/ui-shell/header/header-menu.component.ts, src/ui-shell/header/header.component.ts, src/ui-shell/panel/switcher-list-item.component.ts, src/ui-shell/sidenav/sidenav-item.component.ts
Closes IBM/carbon-components-angular#2223
* Remove inline JS from anchors to enable secure CSP headers
* Set default `_href` value to `#` and return false if `_href` value equals `#` on click.
=> fix: Remove inline js from anchors

src/tag/tag-filter.component.spec.ts, src/tag/tag-filter.component.ts, src/tag/tag.stories.ts
Hello there,
It looks like `ibm-tag-filter` already supported a `disable` argument, but the component needed some adjustment to ensure the behaviour was consistent with being in a disabled state.
**New**
* Some tests for `ibm-tag-filter`
**Changed**
* `ibm-tag-filter` applies an appropriate style to match the `disabled` state
* `onClick` for `ibm-tag-filter` respects `disabled` and won't trigger if the latter is set
**Removed**
* N/A
---
Closes IBM/carbon-components-angular#2061
=> fix(tag): disable state (#2061)

src/input/label.component.ts
Closes IBM/carbon-components-angular#2136
* Prioritize input & textarea over div - this will ensure that the id is not assigned to the div if the textarea & input are wrapped within a div.
=> fix: prioritize input/textarea over div when setting id

.github/CONTRIBUTING.md, .github/workflows/dco.yml
* Adds Carbon DCO workflow
* Adds legal notice in `contribution.md`
`GITHUB_TOKEN` is generated every new JOB.
=> chore: Add carbon DCO workflow

src/timepicker/timepicker.component.ts
Hello there,
This pull request contains the suggestion I outlined in the linked issue regarding the `ibm-timepicker` component appearing odd when used standalone.
**New**
* N/A
**Changed**
* `ibm-timepicker` applies a form item class on its host element (nb. isn't thought to affect existing usages that wrap the component with the same form item class)
**Removed**
* N/A
---
Closes #2290
=> fix(timepicker): add form item style to host (#2290)

src/datepicker/datepicker.component.ts
We are overriding onClose event even if users pass it via flatpickr options, this PR will enable users to know when the flatpickr dialog is closed.
* Emits an event on datepicker close
* Event is being emitted at the end of the onClose because we assign the value to Model in the preceding code
=> feat: Emit an on close event

src/number-input/number.component.ts, src/number-input/number.stories.ts
**Changed**
* Added `data-invalid` attribute to Number Input to apply appropriate styling to buttons (+/-) for invalid state
Before:
After:
=> fix: Add 'data-invalid' attribute to apply appropriate styling to buttons when invalid

src/dropdown/list/dropdown-list.component.ts
Signed-off-by: anemonetea <laz1anastasiya@gmail.com>
Closes carbon-design-system/carbon-components-angular#1409
There was an issue with the styling where disabled items wouldn't get any special styling even though clicking on them would not select the item as expected.
Dropdown before:
Combobox before:
Dropdown after:
Combobox after:
**Changed**
Disabling a list-item within an `ibm-dropdown-list` component styles the item as disabled using existing Carbon SCSS.
Pre-existing SCSS: https://github.com/carbon-design-system/carbon/blob/056efd3400456342b6a6fb4f55dba26b5ff931c1/packages/styles/scss/components/list-box/_list-box.scss#L663-L691
Carbon SCSS uses an attribute selector on `bx--list-box__menu-item` (and not on its children) to apply styling to disabled list-items. So, I've added a …
=> fix: no disabled styling for disabled dropdown items

src/grid/grid.directive.ts
The current implementation lacks reactivity for the input props. Now, when a prop changes the directive will reflect these changes. This feature is required when the application needs to dynamically change the columns' disposition.
Closes carbon-design-system/carbon-components-angular#2385
=> fix: Make column directive reactive for input props

src/combobox/combobox.stories.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.spec.ts, src/dropdown/list/dropdown-list.component.ts, src/grid/grid.directive.ts
The disabled styling was treating ListItem.disabled input as a disabled attribute (i.e. present or not) even though the doc for ListItem says that it is a boolean. Now, ListItem.disabled input is treated as a boolean.
Add tests for disabling a list-item
Fix linting error in grid
Signed-off-by: anemonetea <laz1anastasiya@gmail.com>
**New**
New tests for the presence of a disabled attribute on ibm-dropdown-list components when given an input of `items` with disabled attributes in 3 varieties -- `disabled: true`, `disabled: false`, `disabled: undefined`.
Added disabled examples to the dropdown storybook.
**Changed**
What value we expect the `item.disabled` input to have. It is now consistently treated as a boolean.
"With Observable items" storybook example now uses the same object editable …
=> fix(ibm-dropdown-list): ensure ListItem.disabled is treated as a boolean by styling logic

src/grid/grid.directive.spec.ts, src/grid/grid.directive.ts
Closes carbon-design-system/carbon-components-angular#2430
`ngOnChanges` was never called if no inputs were passed
**Changed**
* added `bx--col` by default
* added UTs to cover this scenario
@zvonimirfras
=> fix(ColumnDirective): fixed missing class if no inputs provided

src/file-uploader/file-uploader.component.spec.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
Closes carbon-design-system/carbon-components-angular#2073
Closes carbon-design-system/carbon-components-angular#2449
**Changed**
* implemented `setDisabledState` for file uploader so that reactive form disable will work
* fixed the issue file uploader was not calling onChangeCallback
=> File uploader not disabling and not calling form onChangeCallback

src/input/label.component.ts
Closes carbon-design-system/carbon-components-angular#2447
in theory the label should only care about its direct children and not deeply seek for inputs/textareas, but at least it shouldn't override existing ids as this would cause issues somewhere else. This is why i added a check if the id already exists
**Changed**
* the id is now applied only if it doesn't exists on inputs/textareas. No changes on how it applies it on divs
=> fix(Label): avoid Label component to override existing ids reuse them instead

src/tabs/tabs.component.ts
Closes carbon-design-system/carbon-components-angular#2467
In CCA v5, we updated the tab types to 'line' & 'contained' to match tab type names in carbon v11.
=> fix: Correct tab header type to 'line' & 'contained'

src/input/label.component.ts
Closes carbon-design-system/carbon-components-angular#2459
added `changeDetectorRef.detectChanges()` to trigger a re-evaluation of the changes. Suggested solution from angular is to use `ngAfterContentInit` instead of `ngAfterViewInit` (https://angular.io/errors/NG0100), but I believe afterViewInit was used to catch elements generated by child components that would only appear at that stage. @reviewers if you believe the suggested change from angular might not break current behaviour i'm happy to apply that change instead.
Screenshot of the error:
**Changed**
* fixed NG0100 error happening when child nodes passed to LabelComponent already define an id
=> Fixed error NG0100 happening on LabelComponent

src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts
Closes: [#2389](https://github.com/carbon-design-system/carbon-components-angular/issues/2389)
Dropdown list was scrollable using mouse but with keyboard list was not scrolling. checked keyboard navigation of dropdown list `navigateList` and found out that upon navigation from arrow keys html elements were missing with scroll behavior. On adding `scrollIntoView` the list scroll is working as expected with keyboard.
Took dropdown list scroll behavior reference from - [carbon design react](https://react.carbondesignsystem.com/?path=/story/components-dropdown--default)
**Before**
**After**
=> fix: dropdown list keyboard scroll not working

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes carbon-design-system/carbon-components-angular#2481
added clear emit for combox's clear button
**New**
clear output emit when combox's clear button is clicked
**Changed**
NA
**Removed**
NA
=> fix: add emit for clear button in combo box

src/dialog/dialog.directive.ts
Closes carbon-design-system/carbon-components-angular#2472
This change improves performance in tables where there are `many` (n) rows with overflow menus. Prior to this change, the setTimeout function in `close` function was being called for each overflow menu on initial load which added `n` number of entries to the list (queue) of active timeouts for handling. Since they all had the same amount of `delay`, the next setTimeout  handler in queue had to wait until the invocation of the handler of the current has completed. So for example with 300 rows, we the last setTimeout in queue would show that it took 20 - 25 seconds for the handler to be called. For more information, view the standard for setTimeout [implementation](https://www.w3.org/TR/2011/WD-html5-20110525/timers.html). …
=> fix: Prevent padding on setTimeout on first change

package-lock.json, package.json, src/tabs/tab-headers.component.ts, tsconfig.spec.json
Closes carbon-design-system/carbon-components-angular#
The tab headers component doesn't handle view resize event and reset scroll properly, which can cause display issues on view resize. This PR fixes that using `ResizeObserver`.
**New**
**Changed**
**Removed**
=> fix(tabs): fix tab headers resize/scroll issue

.storybook/preview.scss, src/grid/column.directive.ts, src/grid/css-grid.stories.ts, src/grid/grid.directive.spec.ts, src/grid/grid.directive.ts, src/grid/grid.module.ts, src/grid/grid.service.ts, src/grid/grid.stories.ts, src/grid/index.ts, src/grid/row.directive.ts
**Changed**
* Assigning initial column classes after view initializes instead of ngOnInit to remove unnecessary SetTimeout which would trigger changeDetection for all child components.
=> fix: Improve grid performance by  preventing unnecessary change detection

src/toggle/toggle.component.spec.ts, src/toggle/toggle.component.ts
Closes carbon-design-system/carbon-components-angular#2508
`aria-checked` can only be applied to elements with role `checkbox`
**Removed**
* Removed invalid accessibility property.
=> fix: Remove invalid aria-checked property in template

src/modal/modal.service.ts
Closes carbon-design-system/carbon-components-angular#2521
When creating a modal via Modal service, setting `hasScrollingContent: false` has no effect.
`hasScrollingContent: data.hasScrollingContent || null,` 
will be set to `null` if `data.hasScrollingContent = false`
`false || null` => `null`
**New**
--
**Changed**
a condition in modal service.
**Removed**
--
=> fix: hasScrollingContent condition in modal service

src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
Closes carbon-design-system/carbon-components-angular#2531
File Uploader had inconsistent behavior in how Forms events would fire between the drag-and-drop version and the standard version of the component. In Reactive Forms, for example, the `(valueChanges)` event wouldn't fire for the drag-and-drop version even though it would fire for the standard version.
**Changed**
`valueChanges` API now behaves consistently across the `drop` version and non-drop version of the `ibm-file-uploader` component.
=> Fix: file uploader valueChanges event to fire for drag-and-drop

src/modal/base-modal.service.ts, src/modal/modal.component.ts
Closes carbon-design-system/carbon-components-angular#2530
**Changed**
* Emits a close event before modal is destroyed
* Destroys modal After 300ms (To late animation complete), after destroy function is called for topmost modal.
=> fix: Emit close event on Escape

src/code-snippet/code-snippet.component.ts
Closes carbon-design-system/carbon-components-angular#2550
This PR adds a `role` and a `aria-readonly` attributes in order to fix the a11y violation. I took those from https://react.carbondesignsystem.com/?path=/story/components-codesnippet--singleline
Before
After
=> fix(code-snippet): Fix an a11y violation

src/toggle/toggle.component.ts
Closes https://github.com/carbon-design-system/carbon-components-angular/issues/2535
This Pr will only add the value of the attribute [value] and [name] to the input element in the toggle.
**Before**
**After**
=> fix(toggle): set the name and value attributes

src/pagination/pagination.component.ts
Closes carbon-design-system/carbon-components-angular#2199
**Changed**
* Updates template to remove redundancy in number of pages displayed. Previously it was `{{num}} page {{num}}`. Now it is `page {{num}}`
=> fix: Update template for pagesUnknown state

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Bubble click event when pill is clicked. This will allow users to stop propagation in components like flyout & prevent them from being closed.
**New**
* bubbles event & type of event to user on `clear` emit
=> fix: Bubble click event

src/tiles/expandable-tile-above.directive.ts, src/tiles/expandable-tile-below.directive.ts, src/tiles/expandable-tile.component.ts, src/tiles/expandable-tile.stories.ts, src/tiles/index.ts, src/tiles/tiles.module.ts
Closes carbon-design-system/carbon-components-angular#2528
**New**
* Allow users to project interactive content
* Adds a `interactive` input for users to initialize tile in interactive state
* Adds new directives to assign fold classes
=> feat: Allow users to project interactive content

src/button/button.directive.ts, src/layout/stack.directive.ts, src/theme/theme.directive.ts
**New**
* Added `<empty string>` as an option for input properties that match the directive selector so users are not REQUIRED to assign values in angular 16+
=> fix: Add empty string option for props that match directive name

src/combobox/combobox.component.ts
Closes carbon-design-system/carbon-components-angular#2628
**Changed**
* Remove event listener on body when drop down closes
* Performance improvements
=> fix: Remove document click event on dropdown close

src/toggletip/toggletip.component.ts, src/toggletip/toggletip.stories.ts
When there are hundreds of toggletips open, there is a significant delay for opening/closing the toggletip. This PR aims to improve the performance of applications that have such scenario.
**Changed**
* Add document:click event only when toggletip is open.
* The event is removed when toggletip is closed.
=> fix: Add event to document only when popover is open

src/code-snippet/index.ts
Closes carbon-design-system/carbon-components-angular#2673
**New**
* Now exporting SnippetType enum with from Code Snippet directory
=> fix: Export code snippet type enum

src/number-input/number.component.ts, src/number-input/number.stories.ts
Closes carbon-design-system/carbon-components-angular#2672
**Changed**
* Updates/writes component `value` when `change` is emitted. This is to make consistent behavior of entering decimal values across Chrome, Firefox & Safari.
**Removed**
* No longer updates value variable on `input` change
=> fix: Update value after change event is emitted

src/file-uploader/file-uploader.component.ts
Closes carbon-design-system/carbon-components-angular#2642
For Drag and drop file uploader component, if `disabled="true"`, we should not allow to drag a file to upload.
**New**
* if `disabled="true"`, I stop file to upload.
Before: 
https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/9fece2f5-39ae-4c1d-bc0d-ea0958d134ee
After: 
https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/b98af467-a73a-404d-a549-fb264d0a3513
=> fix: stop drag and drop while disable file upload input

src/pagination/pagination.component.ts
Closes carbon-design-system/carbon-components-angular#2664
On resize of window, pagination information (i.e. items per page, total items count and page number) are getting hide due to media query on `cds--pagination__text` class. I add another class `cds--pagination__items-count` for important pagination information. On smaller size of window, require information will remain on screen.
**New**
* Add `cds--pagination__items-count` css class to important pagination information display tag.
Before:
https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/92ead07c-a560-433b-83b6-734c115ca2b3
After: 
https://github.com/carbon-design-system/carbon-components-angular/assets/49565062/01135090-0fa2-4f84-b29e-e74c91b50c60
=> fix: make pagination text consist on resize

src/file-uploader/file-uploader.component.ts, src/file-uploader/file.component.ts
Closes carbon-design-system/carbon-components-angular#2286
Adding a role attribute to description and invalid text so screen reader such as JAWS can read them.
https://www.ibm.com/able/requirements/requirements/#4_1_3
This fix is for version 5
**New**
**Changed**
**Removed**
=> fix: enable screen reader to read file upload desc and error

src/ui-shell/panel/panel.component.ts
Closes carbon-design-system/carbon-components-angular#2519
Aria attributes must be valid for the element and ARIA role to which they are assigned
https://www.ibm.com/able/requirements/requirements/#4_1_2
=> fix: remove invalid aria-label for panel

src/table/head/table-head-cell.component.ts, src/table/head/table-head.component.ts
Prior to PR, table header column displayed the header text when in skeleton state. This only occurred when selection columns were shown.
**Changed**
* Hides the table header column when `showSelectionColumn` is false and table is in `skeleton` state
=> fix: Hide table header column data when in skeleton state

src/contained-list/contained-list-item.component.ts, src/structured-list/structured-list.component.ts, src/table/toolbar/table-toolbar.component.ts, src/ui-shell/header/header.component.ts, src/ui-shell/sidenav/sidenav.component.ts
Closes carbon-design-system/carbon-components-angular#2687
**New**
* For contained list, select now accepts `ibm` prefixed selectors
**Changed**
* Readd support for ibm prefixed selectors for shell and table components
=> fix: readd support for ibm prefixed selectors

src/dropdown/dropdown.component.ts
Closes carbon-design-system/carbon-components-angular#2715
The place holder has been removed if the skeleton state is set to true.
**New**
* Hides the placeholder of the `multi-select dropdown` if the it is in the  `skeleton` state.
=> fix for issue #2715

src/dropdown/dropdown.component.ts
Closes #2715 
When the skeleton is set as `true`, placeholder is made as `empty` . 
**Changed**
Assigned the placeholder value as `test` to pass the `npm test`.
=> fix: hide placeholder, label, and helper text when skeleton is enabled

src/combobox/combobox.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts
Closes carbon-design-system/carbon-components-angular#2777
**Changed**
* Prevent dropdown item from scrolling the page when navigating using arrow keys
* Prevent first combobox item from scrolling out of view on initial arrow down
=> fix: prevent first dropdown item from scrolling out of view on initial arrow down

src/contained-list/contained-list-item.component.ts, src/contained-list/contained-list.stories.ts
Enable the capability to associate data with the cds-contained-list-item component, allowing integration with the optional action custom template.
=> Add contained list item action data

src/popover/popover.directive.ts, src/toggletip/toggletip.component.spec.ts, src/toggletip/toggletip.component.ts, src/tooltip/definition-tooltip.component.spec.ts, src/tooltip/definition-tooptip.component.ts, src/tooltip/tooltip.component.spec.ts, src/tooltip/tooltip.component.ts
Closes carbon-design-system/carbon-components-angular#2705
This change allows the tooltip, definition-tooltip and toggletip to be used in OnPush enabled components. Components that are using the default change detection strategy should not be impacted.
**Changed**
* Tooltip has been changed to work with OnPush change detection strategy.
* Definition Tooltip has been changed to work with OnPush change detection strategy.
* Toggletip has been changed to work with OnPush change detection strategy.
=> feat: allow tooltip and toggletip to be used in an OnPush component

.github/workflows/publish.yml, package-lock.json, package.json
ref: #2729
Update ci flow to include provenance statements for npm publishes
**New**
* Now publishing with provenance tokens
**Changed**
* semantic-release bumped to v19
=> ci: Publish packages to npm with provenance statements

src/search/search.component.spec.ts, src/search/search.component.ts, src/search/search.stories.ts
Closes carbon-design-system/carbon-components-angular#2801
Align the behaviour of the expandable search component when pressing escape and clear button similar to the React implementation: https://react.carbondesignsystem.com/?path=/story/components-search--expandable
**Changed**
* OpenChange event gets emitted when closing the search component with expandable option enabled
* The Escape key and clear button now correctly work with the search component with expandable option enabled
=> fix: allow esc and clear to work with the expandable search

src/slider/slider.component.spec.ts, src/slider/slider.component.ts
Closes carbon-design-system/carbon-components-angular#2805
Wrapped the slider thumb in a cds--slider__thumb-wrapper so that the correct styling is applied. Value is now determined by a inset-inline-start. Looked at the React implementation to update this implementation. 
https://react.carbondesignsystem.com/?path=/story/components-slider--default
compared to 
https://angular.carbondesignsystem.com/?path=/story/components-slider--basic
**Changed**
* Thumb styling is correctly applied to the cds-slider
=> fix: wrap slider thumb in a container with correct styling

src/ui-shell/sidenav/side-nav.component.spec.ts, src/ui-shell/sidenav/sidenav-item.component.ts, src/ui-shell/sidenav/sidenav.component.ts, src/ui-shell/sidenav/sidenav.module.ts, src/ui-shell/ui-shell.stories.ts
Closes carbon-design-system/carbon-components-angular#2811
This MR adds a `useRouter` option to the SideNav component (which is `false` by default). 
When the `input` is `true`, `routerLink` will be used instead.
**New**
* adds `useRouter` input to `SideNav`
=> feat: add useRouter property to sidenav

src/ui-shell/sidenav/sidenav-item.component.ts
Closes carbon-design-system/carbon-components-angular#2851
fixed default value for `useRouter` in `sidenav-item.component.ts`
**Changed**
* fixed default value for `useRouter` in `sidenav-item.component.ts`
=> fix: sidenavItem component useRouter should be false by default

src/button/icon-button.stories.ts, src/tooltip/definition-tooptip.component.ts, src/tooltip/tooltip.component.ts
Closes carbon-design-system/carbon-components-angular#2853
Reintroduce `data` input to be passed as `ngTemplateOutletContext` when `description` is a template
**New**
* added `data` input to Tooltip and TooltipDesctiption
**Changed**
* fixed IconButton stories that were showing incorrect input label (`cdsButton` instead of `kind`)
=> feat(Tooltip): expose data input to be passed as template outlet context when rendering the tooltip

src/button/base-icon-button.component.ts, src/button/icon-button.component.ts, src/button/icon-button.stories.ts
Closes carbon-design-system/carbon-components-angular#2855
The icon button did not yet expose the autoAlign input to enable the experimental floating-ui tooltip functionality. 
**New**
* Added experimental autoAlign input on icon button component
=> fix: expose experimental autoAlign input on icon button

src/tooltip/tooltip.component.ts
Closes carbon-design-system/carbon-components-angular#2809
Tooltip will now only open if the timeout actually completes, which means only when the mouse is hovering the element without leaving before the tooltip appears
**Changed**
* resetting the timeouts set on mouseenter and mouseleave before setting new ones to achieve what described above
=> fix(Tooltip): tooltip will open only if the mouse remains on it and no longer overlap with other tooltips

package-lock.json, package.json, scripts/build.sh, src/ng-package.json, src/package.json
`telemetry.yml` file needs to be included in published package to be able to collect telemetry. This PR modifies the build script to include such file.
**Changed**
* Upgrade `@ibm/telemetry-js` to version 1.5.0
* Modify build script to copy `telemetry.yml` to dist folder
* Replace `@carbon/telemetry` with `@ibm/telemetry-js` in `ng-package.json`'s `allowedNonPeerDependencies`
* Replace `@carbon/telemetry` with `@ibm/telemetry-js` in `src/package.json`. Update postinstall script.
=> fix: include ibm telemetry config file in published build

src/datepicker/datepicker.component.ts
Closes carbon-design-system/carbon-components-angular#2857
Prevent initial date input from being reset
**Changed**
* Prevent end date being reset to initial date for range date picker when first set via @Input
=> fix: set initial date to input

src/table/cell/table-radio.component.ts, src/table/head/table-head.component.ts
Closes carbon-design-system/carbon-components-angular#2790
**Changed**
* Applied missing style classes for table radio element and removed inline styling
=> fix: shift header to the right when sticky header and single select are enabled

src/tooltip/tooltip.component.ts
Closes carbon-design-system/carbon-components-angular#2866
Ensure position of popover is correct when toggling icon-button disabled.
**Changed**
* Update view when `disabled` is set to false to retrieve popover content node
=> fix: refresh view on disabled or autoalign changes

src/code-snippet/code-snippet.component.ts
Issue carbon-design-system/carbon-components-angular#2872
Fixes Hide Copy Button when `display` is not inline in the Code Snippet Component
**Changed**
* Fixes Hide Copy Button when `display` is not inline in the Code Snippet Component
Screenshots:
For the following HTML code below:
```
<cds-code-snippet [display]="snippetType" [hideCopyButton]="true">
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis convallis convallis tellus id.
</cds-code-snippet>
```
And the corresponding Typescript snippet:
```
snippetType: SnippetType = SnippetType.multi
```
Before:
After:
=> fix(code-snippet): hide copy button when not inline

src/slider/slider.component.ts
Correct storybook documentation to `SliderModule` instead of `SkeletonModule` for Slider component
**Changed**
* Change storybook documentation to use SliderModule instead of SkeletonModule
=> chore: reference correct module in documentation

src/code-snippet/code-snippet.component.ts, src/code-snippet/code-snippet.stories.ts
Issue went unnoticed due to storybook creating code argument in global scope which was accessible by the component.
**Changed**
* Now text content is correctly copied to clipboard from code element
* **MISC**: Docs now use different variable name than the one used in component to avoid referencing value in global scope.
=> fix: copy inner text or text content of code element

src/slider/slider.component.ts, src/ui-shell/sidenav/side-nav.component.spec.ts, src/ui-shell/sidenav/sidenav-item.component.ts
Closes carbon-design-system/carbon-components-angular#2904
**Changed**
* Now calling `navigate` function on anchor link click which will pass in routeExtras.
=> fix: pass route extras in routerLink

README.md
Closes carbon-design-system/carbon-components-angular#2906
Updates support matrix in readme to include Angular 17. v5 is no longer marked as future release.
=> docs: update support matrix

src/tabs/tab.component.ts, src/tabs/tabs.stories.ts
Closes carbon-design-system/carbon-components-angular#2908
Angular keeps track of projected content even if it is conditionally hidden in component it is passed in. This means the life cycle hooks are only called once instead of every time *ngIf condition is set to true within the projecting component.
**New**
* Allow users to pass in a template as tab content for tabs
* Users can render templates AND/OR projected content
=> fix: Allow users to pass in templates in tabs to allow onDestroy hook to be called for content

src/contained-list/contained-list.component.ts, src/contained-list/contained-list.stories.ts
Closes carbon-design-system/carbon-components-angular#2916
**Changed**
* Add new contained list size classes
* `cds--contained-list--${size}` are deprecated in favor of using `cds--layout--size-${size}` classes. They will be remove in next major version.
=> fix: add new contained size classes

src/ui-shell/sidenav/sidenav-item.component.ts
Closes carbon-design-system/carbon-components-angular#2911
Removes the click handler for the element when using `useRouter`. Adds in all available routeExtras so they get passed along.
=> fix: remove click handler for the anchorlink when useRouter is true

src/treeview/tree-node.component.ts, src/treeview/tree-node.types.ts
Closes carbon-design-system/carbon-components-angular#2936
The component was defining the label input as `string | TemplateRef<any>`, but only using it as a plain string, resulting in being rendered as `[object Object]` when a template is used. This PR is fixing this behaviour and it's introducing `labelContext` following the similar pattern for icon and parent TreeView component.
**New**
* TreeNode `Node` interface now defining `labelContext: any` used when `label` is a `TemplateRef`
**Changed**
* handled the possibility of `label` input being a `TemplateRef` in the html of TreeNode
=> fix(TreeNode): label input not correctly rendered when a TemplateRef is used

README.md
Updates Angular Style Guide in the Readme file
**New**
* added the updated angular style guide link in the readme file
**Removed**
* Removed the obsolete angular style-guide link
=> docs: update angular style guide link

src/combobox/combobox.component.ts
Closes carbon-design-system/carbon-components-angular#2946
When clicking the clear button, check if the component is disabled before clearing the input.
**Changed**
* ComboBox: do not clear input when component is disabled
=> fix: prevent combobox from being cleared when disabled

src/icon/stories/many-icons-demo.component.ts
Closes carbon-design-system/carbon-components-angular#2938
**Changed**
* Delay rendering of all svgs by 1 second to prevent storybook from crashing
=> docs: render all svgs after a delay to prevent browser from freezing

src/table/cell/table-checkbox.component.ts, src/table/head/table-head-checkbox.component.ts
Closes carbon-design-system/carbon-components-angular#2950
**Changed**
* Use hidden label instead of aria label for checkbox (row selection) in table.
=> fix: use hidden label instead of aria label for table checkbox

src/number-input/number.component.ts, src/number-input/number.stories.ts
Closes carbon-design-system/carbon-components-angular#2897
Added readonly state for number input component. Update storybook to support readonly state for number input.
**New**
* `readonly` state for `number-input` component; 
* Doc for how to use readonly in `number-input` storybook;
=> feat: Add readonly state

src/treeview/treeview.component.ts
Closes carbon-design-system/carbon-components-angular#2965
Deeply clone treeNodes to avoid Angular not detecting changes. Not using lodash cloneDeep to avoid performance issue if any node contains a templateRef.
**Changed**
* Treeview now deeply cloning treeNodes received as input
=> fix: deeply clone treeNodes to avoid Angular not detecting changes

src/treeview/tree-node.component.ts, src/treeview/tree-node.types.ts
Closes carbon-design-system/carbon-components-angular#2971
A `gap` (number of px) can be defined to add fixed values to the calculated offset, allowing the freedom to adjust levels alignment.
**New**
* `gap` is a new input in TreeNode, used to be added to the calculated offset
=> feat: allow users to add a custom gap to each node offset

src/input/textarea-label.component.ts, src/input/textarea.stories.ts
Textarea is not mentioned in this epic carbon-design-system/carbon-components-angular#2893
But opening this PR to cover everything under InputModule.
=> feat: add readonly state for textarea

src/treeview/tree-node.component.ts
Closes carbon-design-system/carbon-components-angular#2991
propagating nested nodes toggle event to the parent
**Changed**
* addded `nodetoggle` output to nested tree-nodes
=> fix: node toggle propagation for nested nodes

src/modal/modal.stories.ts
Closes carbon-design-system/carbon-components-angular#3004
=> docs: properly handle close event in simple modal story (#3004)

package-lock.json, package.json, src/checkbox/checkbox-exported-tests.ts, src/exported-tests/component-tests.ts, src/ng-package.json, src/package.json, src/treeview/treeview.stories.ts, src/ui-shell/sidenav/routerlink-extended.directive.ts
* Replace lodash with 'lodash-es' dependency to reduce bundle size
=> fix: replace 'lodash' with 'lodash-es' to reduce bundle size

src/tiles/clickable-tile.component.ts
closes #2996
This PR adds the rel attribute to the anchor tag in the clickable tile for security
Similar security also observed in the anchor tag for overflow menu options component
=> fix: add rel attribute to clickable tile anchor tag

src/modal/modal.component.ts
Closes carbon-design-system/carbon-components-angular#2974
**Changed**:
* Replaced `.cds--modal-content--overflow-indicator` with the new updated class `.cds--modal-scroll-content`.
* Listen for `hasScrollingContent` value change and append `cds--modal-scroll-content` class if true.
=> fix: correctly display modal content overflow indicator

src/checkbox/checkbox-exported-tests.ts, src/ui-shell/sidenav/routerlink-extended.directive.ts
* Correct utility function import from `lodash` to `lodash-es`
=> fix: import utility functions from lodash-es

src/input/text-area.directive.ts, src/input/textarea-label.component.ts, src/input/textarea.stories.ts
Closes carbon-design-system/carbon-components-angular#2891
A way of displaying skeleton was updated as now it needs to handle standard skeleton and fluid skeleton depending on the input property.
=> feat: fluid state for text area

src/pagination/pagination.component.spec.ts, src/pagination/pagination.component.ts
Closes carbon-design-system/carbon-components-angular#3013
**Changed**
The logic that calculates number of pages based on `totalDataLenght` and `itemsPerPage` was updated.
It covers the case in the #3013 
Also covers a scenario when `totalDataLenght` is `0` then `numberOfPages` should be `1`.
New array will be constructed only if number of pages changes. It improves performance as previously `Array` was constructed every time getter was called.
**Added**
* a test to cover this scenario
=> fix: update pagination pageOptions calculation logic

integration/ng18/package-lock.json, src/i18n/en.ts, src/table/head/table-head-expand.component.ts, src/table/head/table-head.component.ts, src/table/stories/app-expansion-table.component.ts, src/table/table-model.class.spec.ts, src/table/table-model.class.ts, src/table/table.component.ts, src/table/table.stories.ts
Closes carbon-design-system/carbon-components-angular#2928
This PR adds a capability to expand / collapse all rows in table.
It can be done by clicking on the icon in the table header or by calling a method on `TableModel`.
=> feat: allow users to expand all table rows

.storybook/manager-head.html
The Angular storybook was using a non-compliant GA tag, which is removed in this PR. I have added onboarding to ibm-common.js, which is the approved tag to add for IBM owned web properties.
**Changed**
* Added `ibm-common.js` and DDO object to manager head for storybook
**Removed**
* non-compliant GA tag
=> chore(ibm-common): removed non-compliant GA tag, onboarded to ibm-common

src/number-input/number.component.ts, src/number-input/number.stories.ts
Closes carbon-design-system/carbon-components-angular#2888
=> feat: fluid state for number input

telemetry.yml
The PR opened a few days ago updating the endpoint URL had the wrong one -- this PR fixes that.
**Changed**
* Changed `https://www-api.ibm.com/ibm-telemetry/v1/telemetry` to `https://www-api.ibm.com/ibm-telemetry/v1/metrics`
=> fix(telemetry): updating endpoint

src/table/table-model.class.spec.ts, src/table/table-model.class.ts
Closes carbon-design-system/carbon-components-angular#3006
=> feat: allow users to delete all table rows

src/progress-bar/progress-bar.component.ts
Correct accessibility attributes in progress-bar
**Changed**
* add 'aria-' prefix to accessibility attributes
=> fix: add 'aria-' prefix to accessibility attributes

package-lock.json, package.json, src/pagination/pagination-nav.stories.ts, src/pagination/pagination-nav/pagination-nav.component.ts, src/pagination/pagination-nav/stories/pagination-nav-story.component.ts
[carbon spec](https://carbondesignsystem.com/components/pagination/usage/)
**New**
* New size property for pagination nav component `sm, md, lg` defaults to `lg` as this is default now.
**Changed**
* had to bump carbon/styles version to 1.67
* updated storybook
https://github.com/user-attachments/assets/6de070bd-8a1e-4bef-811e-25bc16805744
=> feat: allow specifying a size for the pagination nav component

src/structured-list/list-row.component.ts, src/structured-list/structured-list.component.ts, src/structured-list/structured-list.stories.ts
Closes carbon-design-system/carbon-components-angular#2120
**New**
Allow users to:
* tab into structured list
* move by arrow down / up keys
* tab out of structured list
**Changed**
- class `cds--structured-list-row--selected` is now set properly when a row is selected
=> feat: add keyboard accessibility to structured list

integration/ng17/angular.json, src/input/text-input-label.component.ts
Resolve expression has changed (NG0100) for input readonly state 
**Changed**
* Manually trigger change detection when content is initialized
=> fix: refresh view after content is initialized

src/button/icon-button.component.ts, src/button/icon-button.stories.ts
Closes carbon-design-system/carbon-components-angular#3049
Fix regression from v4: this will not hide the tooltip for a disabled icon-button.
**Changed**
* fix: allow tooltip for disabled icon-button
=> Fix: allow tooltip disabled icon button

src/combobox/combobox.component.ts
Closes carbon-design-system/carbon-components-angular#3063
combobox: map disabled values to itemValueKey on clearSelected
=> [fix] 3063 combobox: map disabled values to itemValueKey on clearSelected

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts
Closes #2931
Noticed when in multiselect mode and when defining itemValueKey writeValue cannot properly handle null. 
Added fallback for `null`, added test to make sure as well the model is updated by `itemValueKey` when defined and not with the complete objects.
=> fix: handle null in writeValue when in multiselect mode and itemValueKey is defined

src/pagination/pagination.component.spec.ts, src/pagination/pagination.component.ts
Closes carbon-design-system/carbon-components-angular#3075
The check to show/hide the cdsIcon had a hardcoded value, whereas the select box next to it was using `pageSelectThreshold`. The hardcoded value was replaced by the input variable and unit tests where added for this part of the component
**Changed**
- Replace hardcoded value with `pageSelectThreshold`
=> fix: Remove hardcoded check in pagination select icon condition

src/icon/icon.directive.ts
Browsers may not always render the <title> inside SVG as a tooltip. Ensuring it has a correct namespace improves the cross browser behavior
Closes #3078
**Changed**
* added proper namespace for `title` attribute
=> fix: ensure proper namespace for title attr

src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
Remove ApplicationRef.tick in dropdownlist.
**Removed**
* Remove application ref tick to prevent running change detection for the entire application. Verified removing `tick()` does not cause issues when disabling the first item via storybook. Also verified passing in a new array with setTimeout.
=> fix: remove application ref tick to improve performane

src/i18n/i18n.service.ts
Closes carbon-design-system/carbon-components-angular#3032
The current implementation of the `TranslationStrings` type does not correctly allow for nesting.
This change will fix that.
**Changed**
- fix `TranslationStrings` typing
=> fix: typing for loading translation strings

src/accordion/accordion-item.component.ts, src/breadcrumb/breadcrumb-item.component.ts, src/breadcrumb/breadcrumb.component.ts, src/loading/loading.component.ts, src/number-input/number.component.spec.ts, src/number-input/number.component.ts, src/progress-indicator/progress-indicator.component.ts, src/search/search.component.spec.ts, src/search/search.component.ts
Update components to use On Push, part of  [issue-3066](https://github.com/carbon-design-system/carbon-components-angular/issues/3066)
**Changed**
Select + fix unit tests
Loader
Progress
Number input + fix unit tests
While migrating components to use OnPush change detection, some unit tests started failing. The issue was that the fixture wasn't updating to new input values even when using `fixture.detectChanges()`.
My research revealed that Angular has an API for setting input properties for `fixture.componentRef`: `setInput` ([commit](https://github.com/angular/angular/commit/96c6139c9ab35aa6ab2330a5a79a5906d5c2e8be)) that seems to work as before.
However, using `fixture.componentRef.setInput(propertyName, value)` didn't resolve all test failures. I had to manually trigger change …
=> feat: convert components to use OnPush change detection strategy 

.github/workflows/check-build.yml, integration/ng15/angular.json
CI jobs are starting to fail since `master` branch is using a deprecated GH action. This PR bumps the following actions:
* upload-artifact - v3 -> v4
* download-artifact - v3 -> v4
Additionally, PR bumps budget for angular 15 build. Doubled, in case future dependabot changes increase build size.
=> ci: bump deprecated version of GH action and resolve integration test build issue

README.md
Closes carbon-design-system/carbon-components-angular#2778
Update readme to getting started steps to include icons & required font config for vite
=> docs: add updated getting started steps 

src/toggletip/toggletip.component.ts
**Changed**
* Set **id** & **aria-live** attributes to `cds-popover-content` component to resolve accessibility issue pertaining to **aria-controls**
=> fix: set id to popover content and aria-live attribute
