.npmrc, package.json, scripts/deploy.sh, scripts/prepush.sh, src/banner/banner-content.interface.ts, src/banner/banner.component.ts, src/banner/banner.module.ts, src/banner/banner.service.ts, src/banner/banner.stories.ts, src/banner/toast.component.ts
=> feat(toast): add toast banner

src/button/button.directive.ts, src/button/button.module.ts, src/button/button.stories.ts, src/index.ts
=> feat(button): add button directive

src/input/input.directive.ts
Added documentation to input component 
**New**
* 
**Changed**
* src/input/input.directive.ts
**Removed**
*
=> Added documentation to input component

package.json
=> Update to valid SPDX license

README.md
Added a new step to redefine the default fonts path to prevent any compile warnings and also prevent serving fonts from a CDN.
=> Added a step to set up fonts

README.md
=> Update i18n angular guide link

README.md
=> Add ngx-translate to I18N tooling

src/dialog/dialog.module.ts, src/dialog/dialog.service.ts, src/dialog/overflow-menu/overflow-menu-option.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/dialog/overflow-menu/overflow-menu.directive.ts, src/dialog/overflow-menu/overflow-menu.stories.ts, src/dialog/tooltip/tooltip.component.ts, src/index.stories.ts, src/input/input.stories.ts
adds:
- overflow-menu.directive
- overflow-menu.component
- overflow-menu-pane.component
- overflow-menu-option.component
- related story
closes #43
=> feat: add overflow menu and associated components

src/table/table.stories.ts
Related to IBM/carbon-components-angular#66
**New**
* New sample which demonstrates displaying an overflow menu in the table component
=> Add new sample which demonstrates displaying an overflow menu in the table component

src/button-menu/button-menu-item.component.spec.ts, src/checkbox/checkbox.module.ts, src/combobox/combobox.module.ts, src/content-switcher/content-switcher.component.ts, src/content-switcher/content-switcher.stories.ts, src/dialog/dialog.component.ts, src/dialog/dialog.service.ts, src/dropdown/dropdown.stories.ts, src/dropdown/scrollable-list.directive.ts, src/icon/static-icon.component.ts, src/input/input.module.ts, src/list-group/list-group.component.ts, src/modal/modal.component.spec.ts, src/modal/modal.component.ts, src/sample/sample.component.spec.ts, src/sample/sample.module.ts, src/select/select.module.ts, src/switch/switch.stories.ts, src/table/table.stories.ts, src/tabs/tabs.stories.ts, src/tiles/clickable-tile.component.spec.ts, src/tiles/tile.component.spec.ts, src/utils/position.ts, tslint.json
=> chore: improve lint rules; remove unused imports

src/dialog/overflow-menu/overflow-menu-option.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/i18n/en.json
=>  Fix overflow menu styling and update translation

package-lock.json, package.json
Also it had a security vulnerability
=> chore(package): remove marked as it's no longer needed

src/modal/alert-modal.component.ts, src/modal/modal.service.ts, src/modal/modal.stories.ts
=> fix(modal): upgrade to newer injector api

src/dialog/overflow-menu/overflow-menu.component.ts, src/dialog/overflow-menu/overflow-menu.directive.ts
=> Fix overflow menu visibility for table

src/dialog/overflow-menu/overflow-menu.component.ts, src/table/table.component.ts
=> Update sorting arrows

src/modal/alert-modal.interface.ts, src/modal/modal.service.ts
=> fix(modal): refactor modalService.show and add interfaces

src/accordion/accordion-item.component.ts
Closes IBM/carbon-components-angular #106
Fix DAP issues for Accordion
Set the role to heading and use aria-level per guidelines.
Defaulting level to 3 since must pages have heading level 1 already.
User can override.
Accessibility guidelines
**Changed**
Set the role to heading and use aria-level per guidelines.
=> Fix DAP issues for Accordion

src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
=> Fix DAP issues for combobox and dropdown

src/index.ts
Can we merge this asap please?
=> fix(pagination): Export PaginationModule

src/table/table.component.ts, src/table/table.stories.ts
=> feat(table): add support for custom "no data" template

src/input/input.stories.ts, src/input/label.component.ts
=>  Fix DAP issues for input

scripts/deploy.sh
=> fix(deploy): deploy versioned documentation

package.json, scripts/deploy.sh
This was a sneaky one I only just noticed ... hotfix!
=> fix(docs): fix versioned deployments not actually running

src/dialog/dialog.directive.ts, src/dialog/dialog.service.ts
Improves performance in extreme cases.
closes #224
=> fix(dialog): add singleton click listener for safari fix

src/notification/notification.component.ts
=> fix(notification): Allow falsy `notificationObj`

src/dialog/overflow-menu/overflow-menu-pane.component.ts
=> Fix(overflow menu): Click doesn't work in firefox and IE

package-lock.json, src/dialog/overflow-menu/overflow-menu-option.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/dialog/overflow-menu/overflow-menu.directive.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
=> fix(dialog): fix overflow-menu focussing and arrow keying in IE11

src/notification/notification-display.service.ts, src/notification/notification.component.spec.ts, src/notification/notification.component.ts, src/notification/notification.module.ts, src/notification/notification.service.ts, src/notification/toast.component.ts
=> fix(notification): added NotificationDisplayService

src/i18n/en.json, src/index.ts, src/number-input/number.component.spec.ts, src/number-input/number.component.ts, src/number-input/number.module.ts, src/number-input/number.stories.ts
Closes IBM/carbon-components-angular#125
The library needed a number input component.
**New**
* Added number input component
**Notes** 
This component might be useful for the development of a slider component (#73)
=> feat(number): Add number input component

src/modal/modal-placeholder.component.ts
=> fix(modal-placeholder): Deprecation warning is wrong

src/dialog/tooltip/tooltip.directive.ts
=> fix(tooltip): DAP violation

src/table/table.component.ts
=> fix(table): allow screenreaders to read column sorts correctly

src/i18n/en.json, src/toggle/toggle.component.spec.ts, src/toggle/toggle.component.ts, src/toggle/toggle.module.ts
=> feat(toggle): Add translations to toggle states

src/table/table.component.ts
Should improve the situation in #287 some more.
(technically closes #287 ... again)
=>  fix(table): add aria-live to improve screenreader compat 

src/utils/position.ts
Noticed it was causing some issues with dropdown
=> fix(position): just use body as a reference

src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts, src/file-uploader/file.component.ts, src/modal/modal-header.component.ts, src/pagination/pagination.component.ts
=> update(svgs): alt is not a valid attribute

src/pagination/pagination.component.ts
=> fix(pagination): displays 1 of 0 pages

src/i18n/en.json, src/table/table.component.ts
=> table: Externalize hardcoded strings

src/tiles/tile.component.ts
=> fix(tile): Can't set custom class

src/search/search.component.ts
=> fix(search): clearSearch doesn't issue change event

package-lock.json, package.json, src/progress-indicator/progress-indicator.component.ts, src/progress-indicator/progress-indicator.stories.ts
fixes #384
Adds a vertical variant to the progress-indicator widget, as defined in https://github.com/IBM/carbon-components/pull/1717
=> feat(progress-indicator): adds 'vertical' variant

src/dropdown/dropdown.component.ts
Same as the fix for dialog ... seems like improvements to position.service create conflicts with adding the window scroll
=> fix(dropdown): remove scroll addition to re-fix positioning

src/dropdown/list/dropdown-list.component.ts
closes #408 and brings us in line with the carbon spec ✨
=> fix(dropdown): disallow clicking an item again to clear it

src/combobox/combobox.component.ts
=> fix(combobox): the whole input should trigger the dropdown

src/combobox/combobox.component.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts
As a byproduct this also includes some refinement to AbstractDropdownView
=> feat(dropdown): support passing Observables of Array<ListItem>

package-lock.json, src/table/table.component.ts
=> fix(table): disable sticky header column by default

src/i18n/en.json, src/pagination/pagination.component.ts
=> Update pagination styles to v2

src/tabs/tab.component.ts, src/tabs/tabs.component.ts, src/tabs/tabs.stories.ts
=> feat(tabs): Tabs used as navigation

src/table/table.component.ts
Add footer template so we can customize what is displayed in the footer.
=> Add footer template

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.service.ts
Needed for carbon-addons-wce and neutrino
=> fix(dropdown): make the dropdown.service offset configurable

src/datepicker/datepicker.component.ts
closes #449 
- ensure it has the correct classes when it opens
- ensure it has the correct position
- clean up as much as we can when our element is destroyed
=> fix(datepicker): fixes issue#449

src/notification/notification-content.interface.ts, src/notification/notification.component.ts, src/notification/toast.component.ts
=> chore(notification): improve notification documentation

scripts/deploy.sh
=> use the correct url format

src/dropdown/dropdown.component.ts
=> fix(dropdown): fix disabled state

src/content-switcher/content-switcher-option.directive.ts
Closes IBM/carbon-components-angular#450
Copying fix from v9 to master
=> Fix content-switcher button being unselected bug

src/number-input/number.component.ts
A button with no type attribute acts as type="submit", and will attempt to submit form data when clicked.  Without this change, this component is useless inside an angular form as clicking the spinner buttons will submit the form.
=> Fix number component spinner button types

src/tabs/tab-headers.component.ts, src/tabs/tabs.component.ts, src/tabs/tabs.stories.ts
=> feat(tabs): add before and after content support to tab headers

.travis.yml
=> chore: remove sudo option

src/pagination/pagination.component.ts
=> fix(pagination): fix a11y issues with selects and labels 

src/tag/tag-filter.component.ts
Closes IBM/carbon-components-angular#538
This pull requests adds the possibility to add an action to trigger with the X button on the Filter Tag.
**New**
* Added possibility to give action to X button on Filter Tag
=> Added possibility to give action to the X button on Filter Tag

src/slider/slider.component.ts
=> fix(slider): apply values we received OnInit to the view

src/dialog/dialog-config.interface.ts, src/dialog/dialog.directive.ts
=> fix(dialog): use mouseleave by default

package-lock.json, src/dialog/dialog-config.interface.ts, src/dialog/dialog.directive.ts
closes https://github.com/IBM/carbon-components-angular/issues/552
=> V2 - fix(dialog): use mouseleave by default

src/slider/slider.component.ts
=> V2 - fix(slider): apply values we received OnInit to the view

package-lock.json, package.json
=> fix(date-picker): Update flatpickr

src/tiles/tile-group.component.ts
=> fix(tile-group): dynamic content 

src/dialog/tooltip/tooltip.stories.ts, src/table/table.stories.ts
=> fix tooltip and table link

src/file-uploader/file-uploader.component.ts, src/file-uploader/file.component.ts
=> fix(file-uploader): Button interactions

src/table/table.component.ts, src/table/toolbar/table-toolbar.component.ts, src/ui-shell/header/header.component.ts, src/ui-shell/panel/panel.component.ts, src/ui-shell/sidenav/sidenav.component.ts
=> Add docs to table toolbar and ui shell

src/table/table.component.ts
=> fix(table): skeleton state

src/ui-shell/header/header-action.component.ts, src/ui-shell/ui-shell.stories.ts
=> chore(storybook): Add title to header actions

src/datepicker/datepicker.component.ts
=> fix(datepicker): Make flatpickrOptions an input

.storybook/addons.js, .storybook/config.js, .storybook/polyfills.js, karma-test-shim.js, package-lock.json, package.json
And fixes the build ... oops 😬
=>  update core-js for demos 

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file.component.ts
closes #554 with changes from #537 
closes #556 with changes from #565 
fyi @stanislavgeorgiev
=>  fix: backport fixes to v9 

package-lock.json, src/index.stories.ts
=> Add starter link to welcome page

src/dropdown/list/dropdown-list.component.ts
=> fix(dropdown): Swallows space keys after it's been opened

src/table/table-model.class.ts, src/table/table.component.ts
Related to IBM/carbon-components-angular#626. Can close it after merging the code into master
To test, just add:
```
simpleModel.rowsContext[0] = “error”;
simpleModel.rowsClass[0] = “111";
simpleModel.rowsClass[1] = “222”;
```
in the table.stories.ts, line 414 and then first data row should show contain `<tr class="111">` and second data row should contain the `222` class.
=> feat(Table): Added `rowsClass` property.

src/pagination/pagination.component.ts
- add pageSelectThreshold to configure when to switch to an input
instead of a select
- remove calls to range
closes #633
=> fix(pagination): improve pagination performance

src/number-input/number.component.ts
util is a backend library, it shouldn't be imported
=> fix(number): remove reference to util

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
The datepicker value input wasn't updating or being passed to the underlying inputs properly ... the flatpickr instance had all the correct values, but the inputs appeared blank.
=> fix(datepicker): make value input work correctly

src/table/table.component.ts
=> Update skeleton state

package-lock.json, src/slider/slider.component.ts, src/slider/slider.stories.ts
Closes IBM/carbon-components-angular#582
=> fix(slider): expression changed after check

src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.spec.ts, src/dropdown/list/dropdown-list.component.ts
=> fix(dropdown): clear all not firing selected and selected firing too often

src/breadcrumb/breadcrumb-item.interface.ts, src/breadcrumb/breadcrumb.component.ts, src/breadcrumb/breadcrumb.stories.ts, src/datepicker/datepicker.stories.ts
=> feat(breadcrumb): add template option for items

src/input/input.stories.ts, src/search/search.component.html, src/search/search.component.ts, src/search/search.stories.ts
=> Add autocomplete input

src/content-switcher/content-switcher.stories.ts
Closes IBM/carbon-components-angular#660
**Changed**
*  Update content switcher sample to emit unique selected events
=> chore(contentswitcher): Update content switcher sample to emit unique selected events

src/tiles/tiles.stories.ts
=> chore(tile): Fix doc

src/combobox/combobox.component.ts, src/datepicker-input/datepicker-input.component.ts, src/dropdown/dropdown.component.ts, src/select/select.component.ts, src/slider/slider.component.ts, src/timepicker-select/timepicker-select.component.ts, src/timepicker/timepicker.component.ts
=> fix(form components): Remove label when null

src/dialog/tooltip/tooltip.component.ts
=> fix(tooltip): pointer position

src/tabs/tab-headers.component.ts, src/tabs/tabs.component.ts
=> Add aria-label and focusout to tabs

package-lock.json, src/dialog/overflow-menu/overflow-menu-option.component.ts, src/modal/modal.component.ts
=> fix(overflow-menu): change after checked errors

src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#608
TODO: add to v3, cause this is a pretty slick feature
=> fix(dropdown): selected emitting on update

src/content-switcher/content-switcher-option.directive.ts
=> fix(content-switcher): emit selected on focus

README.md
Due to lot of package require icons it should install at first
Improved docs
=> Added angular icon package in README

src/modal/modal.component.ts
Removed unwanted tab-index from the modal which is causing 
**Removed**
* Removed tab-index
=> Fix unwanted tab index for modal

src/dropdown/list/dropdown-list.component.ts
=> v9: fix(dropdown): nulls emitted by select

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#640
=> Update updateSelected update pill on multi select

src/i18n/i18n.module.ts, src/pagination/pagination.component.ts, src/table/table.component.ts, src/table/toolbar/table-toolbar.component.ts, src/tiles/expandable-tile.component.ts, src/toggle/toggle.component.ts
=>  fix(i18n): Overridable type resolution 

src/tiles/clickable-tile.component.ts, src/tiles/tiles.stories.ts, src/ui-shell/header/header-item.component.ts, src/ui-shell/sidenav/sidenav-item.component.ts, src/ui-shell/ui-shell.stories.ts
=> Better routing support for tiles and sidenav

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
=> fix(datepicker): account for late DOM initlization when calling flatpickr

package-lock.json, src/dialog/dialog-config.interface.ts, src/dialog/dialog.directive.ts, src/dialog/dialog.service.ts, tsconfig.json
=> fix(dialog): allow easier dialog control through the dialog service

src/table/table.stories.ts, tsconfig.json
=> Update table storybook to include short option in knobs

src/button/button.directive.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts, tsconfig.json
Closes #735 
Added an option to change the size of the upload button for the file uploader. 
Added getters to ibmButton to be able to change configuration after initialization.
Removed onInit from ibmButton.
=> feat(File Uploader) Add option to change the size of upload button

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts, tsconfig.json
Closes IBM/carbon-components-angular#721
closes #741
=> fix(dropdown): model value not propagating correctly in some cases

src/table/body/table-body.component.ts
=> fix(table): pass down showSelectionColumn

src/notification/notification-content.interface.ts, src/notification/notification.component.ts, src/notification/notification.stories.ts, src/notification/toast.component.ts, tsconfig.json
=> feat(Notification) Add low contrast option for notification

src/file-uploader/file-item.interface.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.module.ts, src/file-uploader/file-uploader.stories.ts, src/file-uploader/file.component.ts
=> feat(FileUploader) Update error state for file uploader component

src/dropdown/dropdown.component.spec.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.module.ts, src/dropdown/dropdown.stories.ts
=> feat(dropdown) Add invalid and invalidText inputs

src/tiles/selection-tile.component.ts, src/tiles/tile-group.component.ts
=> fix(tiles): update DOM properties after the view is stable

src/slider/slider.component.ts
Primarily fixes form #639
closes #797
=> fix(slider): apply fixes from v3

src/ui-shell/header.component.ts
Closes IBM/carbon-components-angular#779
=> fix(ui-shell): add header router changes from v3

src/ui-shell/header/header.component.ts, src/ui-shell/ui-shell.stories.ts
=> feat(ui-shell): Add ability to set href on header banner

src/dropdown/dropdown.component.ts
=> fix(Dropdown): add ApplicationRef to update view

src/select/select.component.ts
=> fix(select): align inline select arrow

src/checkbox/checkbox.component.spec.ts
=> Update tests for checkbox

src/ui-shell/header/hamburger.component.ts, src/ui-shell/header/header.module.ts
=> fix(ui shell): change to correct hamburger icon

src/file-uploader/file-uploader.component.ts
=> fix(file uploader): Prevent fileChanges event from getting fired on init

src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
=> fix(dropdown): emit empty array when last selected item is unselected

package-lock.json, package.json, src/ui-shell/sidenav/sidenav-menu.component.ts
Closes IBM/carbon-components-angular#795
=> fix(ui-shell): sidenav change after check

src/table/body/table-body.component.ts, src/table/body/table-row.component.ts, src/table/cell/table-radio.component.ts, src/table/head/table-head.component.ts, src/table/stories/app-table.component.ts, src/table/table.component.ts, src/table/table.module.ts
- restore old row selection behaviour
- add radio row selection
Closes IBM/carbon-components-angular#375
=> feat(table): add radio row selection

src/datepicker/datepicker.component.ts
=> fix(date picker): update dates on UI on focus change

src/table/head/table-head.component.ts
=> fix(table): prevent extra <th> from stickyHeader from taking space

src/datepicker/datepicker.component.ts
=> fix(date picker): prevent error on form reset

src/dialog/tooltip/tooltip-definition.component.ts, src/dialog/tooltip/tooltip-definition.stories.ts
=> fix(tooltip): pick up A11y changes for tooltip definition

src/dialog/tooltip/tooltip-icon.component.ts, src/dialog/tooltip/tooltip-icon.stories.ts
=> fix(tooltip): pick up A11y changes for tooltip icon

src/table/table.component.spec.ts
=> Update tests for table

src/dialog/dialog.directive.ts
=> fix(dialog): open with enter or space after check

src/pagination/pagination.component.spec.ts
=> Add tests to pagination

src/tiles/selection-tile.component.ts
=> fix(selection tile): add ability to make selections using keyboard

src/i18n/i18n.service.ts
=> fix(i18n): unsubscribe previous subscription before assigning a new subscription

src/dropdown/dropdown.component.ts
=> fix(dropdown): Clear all selected options when number icon is clicked

src/search/search.component.ts
=> feat(search): add output to listen to open and close event of toolbar search

scripts/build.sh
Closes IBM/carbon-components-angular#909
=> fix #909 add readme and package.json to dist

src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
Closes #836 
**New**
* It is now possible to change the placement of the overflow menu to the top position.
=> feat(overflow menu): add top placement configuration for overflow menu

src/ui-shell/ui-shell.stories.ts
=> fix(side-nav): hide/show left nav

src/pagination/pagination.component.ts
=> fix(Pagination): fix alignment issues on IE11

src/content-switcher/content-switcher.component.spec.ts
=> Add tests to content switcher

src/modal/alert-modal.component.ts
Content needs to be focusable to allow keyboard users the ability to scroll the content.
=> fix(modal): scroll overflow content

src/slider/slider.component.ts
Closes IBM/carbon-components-angular#932
=> fix(slider): Stop trapping all keys and listen only for the arrow keys.

.gitignore, package-lock.json, src/table/body/table-row.component.ts, src/table/cell/table-data.component.ts, src/table/data-grid-interaction-model.class.ts, src/table/head/table-head-cell.component.ts, src/table/head/table-head.component.ts, src/table/table-adapter.class.ts, src/table/table-header-item.class.ts, src/table/table-item.class.ts, src/table/table-model.class.ts, src/utils/scroll.ts
Closes IBM/carbon-components-angular#931
=> feat(table): add support for col and row spans

src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
=> feat(table): show blue action bar only when actions are defined

package-lock.json, package.json, src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts, src/file-uploader/file.component.ts
=> feat(File Uploader): Add drag and drop option

src/table/cell/table-data.component.ts, src/table/head/table-head-cell.component.ts, src/table/head/table-head.component.ts, src/table/stories/app-custom-table.component.ts, src/table/stories/app-expansion-table.component.ts, src/table/stories/app-no-data.component.ts, src/table/stories/app-overflow-table.component.ts, src/table/stories/app-pagination-table.component.ts, src/table/stories/app-table.component.ts, src/table/table.stories.ts
=> fix(table): prevent skeleton state from overlapping table header content

src/dropdown/list/dropdown-list.component.ts
=> fix(dropdown): check if getSelected returns empty array instead of null

src/file-uploader/file-uploader.component.ts
Changed dragOver scope to fix production build. Also moved declaration before protected fields.
=> fix(file-uploader): change dragOver scope to fix production build

src/combobox/combobox.component.ts
=> fix(combobox): Prevent list reset for multi select combobox after selection

src/notification/notification-content.interface.ts, src/notification/notification.component.ts, src/notification/notification.module.ts, src/notification/notification.stories.ts
=> feat(notification): add support for actions

src/table/head/table-head-checkbox.component.ts
Closes IBM/carbon-components-angular#992
=> fix(table): add overridable type import

src/number-input/number.component.ts
=> fix(number): display nothing when form control value is null

src/notification/notification-content.interface.ts, src/notification/notification-subtitle.directive.ts, src/notification/notification-title.directive.ts, src/notification/notification.component.spec.ts, src/notification/notification.component.ts, src/notification/notification.module.ts, src/notification/notification.stories.ts, src/notification/toast-caption.directive.ts, src/notification/toast-subtitle.directive.ts, src/notification/toast-title.directive.ts, src/notification/toast.component.ts, src/table/head/table-head-checkbox.component.ts
=> feat(Notification): Add support for custom content and add story example

package-lock.json, package.json
Updates the `carbon-components` dev dependencies to version `10.9.2`
=> update carbon-components dev version

src/dropdown/dropdown.service.ts
=> feat(dropdown): flip position of dropdown menu if outside of right view port

src/table/head/table-head.component.ts
=> fix(table): check/change scrollbar width in the next cycle

src/table/table-model.class.ts
Closes IBM/carbon-components-angular#1019
**New**
**Changed**
**Removed**
=> fix(table): select all when there is only one row

src/dropdown/dropdown.component.ts, src/i18n/en.ts
Closes IBM/carbon-components-angular#1024
=> fix(dropdown): Externalize clear button tooltip text.

src/modal/alert-modal.component.ts, src/modal/alert-modal.interface.ts, src/modal/modal.component.ts, src/modal/modal.service.ts, src/modal/modal.stories.ts
=> feat(modal): add size property

src/button/button.directive.ts, src/button/button.stories.ts
Closes IBM/carbon-components-angular#1041
=> fix(button): add field size

src/datepicker/carbon-flatpickr-month-select.ts
Closes IBM/carbon-components-angular#1012
=> fix(datepicker): check for yearElements existence before rendering month select

src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
Closes IBM/carbon-components-angular#1050
Add check for when acceptable extensions is empty
=> fix(file-uploader): add check for when acceptable extensions is empty

src/index.ts
=> export skeleton module in index.ts

src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
Closes IBM/carbon-components-angular#1045
{{adds a check for length and multi-select property in function onDrop}}
=> fix(file-uploader): add length check to prevent multiple input from being accepted when multiselect is disabled

src/utils/animation-frame.service.ts, src/utils/utils.module.ts
Closes IBM/carbon-components-angular#1029
=> fix(AnimationFrameService): use runOutsideAngular to prevent RAF triggering change detection

src/table/head/table-head-cell.component.ts
=> fix(table): allow span to be included in the table header in skeleton mode

src/dialog/dialog.directive.ts, src/dialog/dialog.service.ts, src/dialog/tooltip/tooltip.stories.ts
=> fix(dialog): unsubscribe to local close subscriptions in OnDestroy

package-lock.json, package.json
Updating @carbon/utils-position version
**New**
* new version 1.1.3 of @carbon/utils-position consumed
=> fix: updated @carbon/utils-position version

.github/CODE_OF_CONDUCT.md, README.md
Just some minor updates to the readme and code of conduct
=> update code of conduct

src/table/stories/app-pagination-table.component.ts, src/table/stories/app-table.component.ts, src/table/table-model.class.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
Closes #1033 
closes #1065
Add `onCancelSelected` event which gets emitted when tool bar cancel button is clicked. Also remove duplicate story from storybook.
=> feat(table): add onCancelSelected event

src/table/body/table-body.component.ts, src/table/body/table-row.component.ts, src/table/stories/app-custom-table.component.ts, src/table/stories/app-expansion-table.component.ts, src/table/stories/app-overflow-table.component.ts, src/table/stories/app-pagination-table.component.ts, src/table/stories/app-table.component.ts, src/table/table.component.ts
=> fix(table): bubble up click event when row item is clicked

src/index.ts
added export for date picker input module
Closes IBM/carbon-components-angular# https://github.com/IBM/carbon-components-angular/issues/1067
**New**
**Changed**
**Removed**
=> added export for datepicker input module

src/table/table-model.class.ts
First item off the docs list: checked.
=> Add TableModel docs

src/ui-shell/sidenav/sidenav-item.component.ts, src/ui-shell/sidenav/sidenav-menu.component.ts, src/ui-shell/ui-shell.stories.ts
=> feat(ui shell): add indicator on sidenav menu if there is an active child

src/index.ts
=> fix(toggle): export toggle

package.json
**New**
**Changed**
**Removed**
=> fix semantic release tag format

src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#1123
Dropdown will now wait for the items to be ready if they comes from an observable
**Changed**
* Dropdown-List now exposes an `onItemsReady` function
* Dropdown will propagate values coming from FormControl only after items are ready
=> fix: Dropdown component will now wait for observable before propagating values from FormControl

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/dropdown/list/dropdown-list.component.ts, src/i18n/en.ts, tsconfig.json
Fixes #1088 
Change-log:
- all aria-labels and some titles were hard-coded
- dropdown items didn't highlight title (as its content)
- combobox story with custom templates was not testable
=> fix(#1088): combobox didn't allow aria-labels to be changed

src/combobox/combobox.component.ts, src/combobox/combobox.module.ts
Fixes import problems with `combobox.d.ts`
=> fix(combobox): import overridable

src/utils/scroll.ts
=> fix(dialog): account for partial visibility in visibility calculation

src/table/table.component.ts
=> fix(table): create a new subscription instance when a new table model is set

src/modal/modal.component.ts
=> feat(modal): Add overflow indicator

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/combobox/combobox.module.ts, src/combobox/combobox.stories.ts, src/datepicker-input/datepicker-input.component.ts, src/dropdown/list/dropdown-list.component.ts, src/i18n/en.ts, src/modal/modal.component.ts, src/table/table.component.ts, src/utils/scroll.ts, tsconfig.json
=> updating breaking-changes from master

package.json
BREAKING CHANGE: Angular 9 support
BREAKING CHANGE: Removed deprecated options and functionality (see upgrade guide for details)
BREAKING CHANGE: Dialog refactor
BREAKING CHANGE: Modal refactor
BREAKING CHANGE: `@carbon/icons-angular` updated to v11
BREAKING CHANGE: Switched packaging to APF
=> v4 prerelease

src/accordion/accordion-item.component.ts
Closes IBM/carbon-components-angular#1058
Add the functionality to have template inserted in the title/header of an Accordion item.
**New**
**Changed**
**Removed**
=> Add template option for title

src/tabs/tab-headers.component.ts, src/ui-shell/panel/panel.component.ts, src/ui-shell/sidenav/sidenav.component.ts
=> fix(ui-shell and tabs): fix ui-shell accessibility issues and fix tab CSP violation

src/table/table-container.component.ts
=>  fix(table-container): remove position relative from container

src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts
=> fix(dropdown): make clear button accessible via keyboard

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
New input was added to combobox component to limit the characters on the input when the developer requires it, in this case the input is called `maxLength`
**New**
* Sets maxlength attribute to input tag when `maxLength` input is defined
=> feature: add input to set max length to the input inside combobox

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
=> fix(combobox): allow selected values to be updated through setValue

src/modal/alert-modal.component.ts, src/modal/alert-modal.interface.ts, src/modal/modal.component.ts, src/modal/modal.service.ts
=> fix(modal): add automatic detection of scrollable elements

src/checkbox/checkbox.component.ts, src/code-snippet/code-snippet.component.ts, src/combobox/combobox.component.ts, src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/dialog/dialog.component.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts, src/file-uploader/file-uploader.component.ts, src/input/label.component.ts, src/modal/alert-modal.component.ts, src/modal/modal.component.ts, src/modal/overlay.component.ts, src/notification/notification.component.ts, src/placeholder/placeholder.component.ts, src/search/search.component.ts, src/select/select.component.ts, src/slider/slider.component.ts, src/structured-list/list-row.component.ts, src/table/stories/app-custom-table.component.ts, src/table/stories/app-expansion-table.component.ts, src/table/stories/app-overflow-table.component.ts, src/table/stories/app-pagination-table.component.ts, src/tabs/tab-header.component.ts, src/tabs/tab-headers.component.ts, src/tabs/tabs.component.ts, src/tiles/selection-tile.component.ts, src/toggle/toggle.component.ts
=> fix: prevent viewchildren from being accessed before initilization

package.json, src/dropdown/dropdown.component.ts
=> fix(dropdown): fix accessibility issues - v3

src/radio/radio-group.component.ts, src/radio/radio.stories.ts
This allows the view to be updated when selected value is set with `setValue`
=> fix(radio): allow value to be set through setValue

package.json, src/dialog/dialog-config.interface.ts, src/dialog/dialog.directive.ts, src/dialog/tooltip/ellipsis-tooltip.directive.ts, src/dialog/tooltip/tooltip.stories.ts
=> feat(ellipsis tooltip): toggle dialog on hover - v3

package.json, src/radio/radio-group.component.ts, src/radio/radio.stories.ts
=> fix(radio): allow value to be set through setValue - v3

package.json, src/pagination/pagination.component.ts
=> fix(pagination): change ariaLabel attribute binding - v3

src/checkbox/checkbox.component.ts, src/radio/radio.component.ts, src/table/cell/table-checkbox.component.ts, src/table/cell/table-radio.component.ts, src/table/head/table-head-checkbox.component.ts, src/table/head/table-head.component.ts, src/table/table-model.class.ts
=> fix(table): fix accessibility issues - v3

package.json, src/dialog/dialog.directive.ts, src/dialog/tooltip/tooltip.directive.ts, src/dialog/tooltip/tooltip.stories.ts
=> feat(dialog): Expose offset as an input - v3

src/structured-list/structured-list.component.ts
=> fix(structured-list): allow rows to be focusable when selection is set to true

src/radio/radio.component.ts, src/table/stories/app-table.component.ts, src/table/table-adapter.class.ts, src/table/table.component.ts, src/table/table.stories.ts
=> fix(table): prevent multiple single select radios from being selected

src/structured-list/structured-list.component.ts
=>  fix(structured-list): allow rows to be focusable when selection is set to true - v3

src/dropdown/dropdown.component.ts
=> fix(dropdown): fix accessiblity issue

src/notification/notification.component.ts, src/notification/notification.module.ts, src/notification/toast.component.ts
=> fix(notification): add missing notification icon

src/modal/alert-modal.component.ts
Closes IBM/carbon-components-angular#1301
Added propert `@Optional()` decorator for optional inputs
**Changed**
* added `@Optional()` decorator for AlertModal's inputs
=> fix(AlertModal): added @Optional decorator for optional inputs

src/datepicker/datepicker.component.ts
=> fix(datepicker): sync up dates on calendar close

src/checkbox/checkbox.component.ts, src/radio/radio.component.ts, src/table/cell/table-checkbox.component.ts, src/table/cell/table-radio.component.ts, src/table/head/table-head-checkbox.component.ts, src/table/head/table-head.component.ts, src/table/table-model.class.ts
=> fix(table): fix accessibility issues

src/checkbox/checkbox.component.ts
=> fix(checkbox): update classes to fix label padding

src/datepicker/datepicker.component.ts
=> fix(datepicker): fix weekday inconsistencies

src/combobox/combobox.component.ts
=> fix(combobox): add missing disabled classes

src/dialog/dialog.directive.ts, src/dialog/tooltip/tooltip.directive.ts, src/dialog/tooltip/tooltip.stories.ts
=> feat(dialog): Expose offset as an input

src/file-uploader/file-uploader.stories.ts, src/file-uploader/file.component.ts
=> fix(file uploader): allow same file to be uploaded again after removal

src/file-uploader/file-uploader.stories.ts, src/file-uploader/file.component.ts
=> fix(file uploader): allow same file to be uploaded again after removal - v3

src/combobox/combobox.component.ts
=> fix(combobox): use directive version of close icon

src/checkbox/checkbox.component.spec.ts, src/checkbox/checkbox.component.ts, src/checkbox/checkbox.stories.ts
=> fix(checkbox): prevent setting id from disabling checkbox input

src/combobox/combobox.component.ts
=> fix(combobox): prevent placeholder text from being truncated

src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts
=> feat(file uploader): add disable input - v3

src/select/select.component.ts, src/select/select.stories.ts
=> fix(select): add guard before setting select value

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes #1342
Closes #1341 
Closes #1338 
Closes #1340
Closes #1334
=> fix(combobox): prevent selected value from resetting when key is entered

src/tabs/tab-header.component.ts, src/tabs/tab-headers.component.ts
=> feat(tabs): add title to tab headers

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
Closes https://github.com/IBM/carbon-components-angular/issues/1348
=> feat(datepicker): add individual invalid state

src/combobox/combobox.component.ts
=> fix(combobox): hide close button when programmatically deselecting items

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts
Closes IBM/carbon-components-angular#1362
This is implementing the `selectionFeedback` behaviour that you can find in the react version of ComboBox and Dropdown components
**New**
* `selectionFeedback` property can now be configured for ComboBox
* `selectionFeedback` property can now be configured for Dropdown
P.S.:
I was also fixing the invalid icon misalignment in ComboBox, but pulling latest code i found someone fixed it as well.
=> Implemented `selectionFeedback` for ComboBox and Dropdown

src/i18n/en.ts, src/ui-shell/header/hamburger.component.ts
=> fix(ui-shell): apply correct title and aria-label on hamburger menu

src/tiles/selection-tile.component.ts
=> fix(selection-tile): prevent expression change error when selected is initialized

src/datepicker-input/datepicker-input.component.ts
=> fix(datepicker): make invalid styling consistent

src/tiles/expandable-tile.component.ts
=> fix(expandable tiles): prevent expression changed errors when put in tabs

src/select/select.component.ts
=> fix(select): allow value to be set with reactive forms in on init

src/datepicker/datepicker.component.ts
=> fix(datepicker): prevent date range from being out of sync in reactive forms/ngModel

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes IBM/carbon-components-angular#1379
Implemented `theme` property for ComboBox in the same way it is implemented for Dropdown
**New**
* `theme` property is now available and can assume values of `dark` or `light`
=> fix(ComboBox): implemented missing theme property

src/checkbox/checkbox.component.ts, src/search/search.component.html, src/search/search.component.ts
Added 'lg' ibm-search
**New**
* Added 'lg' ibm-search
=> Feature: 'lg' ibm-search

src/dropdown/dropdown.component.ts
Add support of TemplateRef for invalidText input of dropdown as in other components (for example https://github.com/IBM/carbon-components-angular/blob/master/src/combobox/combobox.component.ts#L138 )
**Changed**
* Add support of TemplateRef for invalidText input
=> feat(dropdown) Add support of TemplateRef for invalidText input

src/button/button.stories.ts, src/table/table.stories.ts
=> fix(storybook demos): organize button icons to be inline with button text for safari

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts, src/input/input.directive.ts, src/input/input.stories.ts, src/number-input/number.component.ts, src/number-input/number.stories.ts, src/search/search.component.html, src/search/search.component.ts, src/search/search.stories.ts, src/select/select.component.ts, src/select/select.stories.ts
=> feat(form input fields): add missing size inputs and classes

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/combobox/combobox.module.ts, src/combobox/combobox.stories.ts
=> fix(combobox): allow combobox list items to overflow if there are scrollable parents

src/pagination/pagination.component.ts, src/pagination/pagination.stories.ts
=> fix(pagination): allow itemsPerPage dropdown to be disabled

src/tabs/tab-header.component.ts
=> fix(tabs): add title on next change detection cycle

src/table/table.stories.ts, src/table/toolbar/table-toolbar-search.component.ts
=> fix(table search): add NG_VALUE_ACCESSOR to component metadata

src/timepicker-select/timepicker-select.component.ts
=> fix(timepicker select): use directive version of icon

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
=> fix(datepicker): prevent duplication of ids

src/dropdown/dropdown.module.ts, src/dropdown/list/dropdown-list.component.ts
=> feat(dropdown list): add checkmark to selected list item

package.json, src/file-uploader/file-uploader.component.ts, src/search/search.component.html
The build was failing, this should fix that!
=> chore: fix build

src/content-switcher/content-switcher-option.directive.ts, src/content-switcher/content-switcher.component.ts
Closes IBM/carbon-components-angular#1244
Supersedes #1245
=> fix(content-switcher): only emit selection once

src/checkbox/checkbox.component.ts, src/combobox/combobox.component.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/number-input/number.component.ts, src/search/search.component.ts, src/select/select.component.ts, src/timepicker/timepicker.component.ts
Closes IBM/carbon-components-angular#1225
Compilation of a number of fixes/enhancements for v3
=> fix: backport fixes to v3

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes IBM/carbon-components-angular#1426 (for v3)
=> fix(combobox): emit empty string when search cleared

scripts/build.sh
**New**
**Changed**
**Removed**
=> disable docgen until build times can be fixed

scripts/deploy.sh
**New**
**Changed**
**Removed**
=> disable doc deployment until doc build time is fixed

src/dropdown/list/dropdown-list.component.ts
=> fix(dropdown-list): emit select event if a default selected item is present

src/notification/notification.component.ts, src/notification/toast.component.ts
=> fix(notification): prevent action button from overlaying notification border

src/dialog/dialog.directive.ts, src/dialog/dialog.service.ts
=> fix(dialog): prevent dialog from remaining open

src/table/table.module.ts
=> Export table row class

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts
=> fix(dropdown): modify validation of writtenValue to allow initialization with a numerical value

src/search/search.component.html, src/search/search.component.ts
=> feat(search): add search event

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
=> feat(combobox): add itemValueKey input

src/list/list.directive.ts
=> fix(list): prevent nested from returning null

src/input/label.component.ts
Closes IBM/carbon-components-angular#1454
=> fix(label): move the helper text below the input

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts
=> feat(dropdown): Add automatic detection of dropUp and allow dropUp to be overridden

src/ui-shell/header/header-item.component.ts, src/ui-shell/ui-shell.stories.ts
=> feat(ui-shell header): Add selected header style

src/dialog/tooltip/tooltip.stories.ts, src/tag/tag-filter.component.ts
=> fix(tag-filter): prevent click propagation

src/radio/radio-group.component.ts
Closes IBM/carbon-components-angular#1464
=> fix(radio group): update selected values from writeValue

src/datepicker/datepicker.component.ts
Closes IBM/carbon-components-angular#1504
=> fix(datepicker): writeValue not propagating values

src/datepicker/datepicker.component.ts
Closes IBM/carbon-components-angular#1010
=> fix(datepicker): deprecate pattern input, and introduce inputPattern

package-lock.json, package.json, src/dialog/overflow-menu/overflow-menu.component.ts, src/table/head/table-head-cell-label.directive.ts, src/table/head/table-head-cell.component.ts, src/table/index.ts, src/table/stories/app-custom-table.component.ts, src/table/table.module.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
=> feat(table): Add size input for toolbar and add missing header classes

package-lock.json, src/i18n/en.ts, src/pagination/pagination.component.ts
Closes IBM/carbon-components-angular#1492
=> fix(pagination): add singular translation strings

src/combobox/combobox.component.ts
Pass down autocomplete attribute to native input
**New**
* autocomplete input for combobox
=> feat(combobox): pass down autocomplete to native input

src/search/search.component.html, src/table/table.component.ts, src/table/table.stories.ts, src/table/toolbar/table-toolbar.component.ts
Closes #1493 
Ports over changes from #1511 and #1241 to v3
=> fix(table): Fix table focus/tabindex handling and allow toolbar search to be focusable

src/table/head/table-head-checkbox.component.ts
=> fix(table checkbox): prevent selectAll checkbox from emitting 3 times per click

src/structured-list/list-row.component.ts
=> fix(list-row): allow clicks to propagate to children

.storybook/preview.scss, src/table/stories/app-custom-table.component.ts, src/table/stories/app-expansion-table.component.ts, src/table/stories/app-no-data.component.ts, src/table/stories/app-overflow-table.component.ts, src/table/stories/app-pagination-table.component.ts, src/table/stories/app-table.component.ts
Closes IBM/carbon-components-angular#1532
Fixed storybook styles for correct display stories.
=> fix(storybook): now demo will work as expected. fix #1532

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
=> fix(combobox): prevent combobox options from shrinking

src/number-input/number.component.ts
Fix location of helper text to match latest:
Fixes: https://github.com/IBM/carbon-components-angular/issues/1548
Before:
After:
=> fix(number): fix placement of helper text in number input

src/accordion/accordion.component.ts, src/accordion/accordion.stories.ts
Add align input so user can select end or start alignment. This is from the carbon docs:
Fixes: https://github.com/IBM/carbon-components-angular/issues/1549
=> feat(accordion): adding align input to accordion

src/tiles/tile.component.ts, src/tiles/tiles.stories.ts
Adding light theme to tiles.
Open to suggestions for input name
=> feat(tile): adding light theme to tiles

src/pagination/pagination.component.ts, src/pagination/pagination.stories.ts
Closes IBM/carbon-components-angular#1574
=> fix(pagination): allow disabling of page inputs

src/pagination/pagination.component.ts, src/pagination/pagination.stories.ts
Closes IBM/carbon-components-angular#1405
=> fix(pagination): allow hiding page inputs

src/dialog/dialog-config.interface.ts, src/dialog/dialog.component.ts, src/dialog/dialog.directive.ts, src/dialog/dialog.service.ts, src/dialog/index.ts, src/dialog/overflow-menu/overflow-menu-pane.component.ts
Closes IBM/carbon-components-angular#1596
=> feat(dialog): add reasons to shouldClose, expose shouldClose, and add closeWhenHidden

src/ui-shell/header/header.component.ts
=> fix(accessibility): fix redundant role

package-lock.json, src/combobox/combobox.component.ts
closes #1605
**New**
**Changed**
**Removed**
=> fix(combobox): aria-label

src/input/label.component.ts
Closes IBM/carbon-components-angular#1609
=> fix(label): set element ids on newer angular

.storybook/addons.js, package-lock.json, package.json
Adds Google Analytics to the storybook. It'll be interesting to see if we get _any_ data from this 😆
=> chore(storybook): add analytics

package-lock.json, src/dialog/overflow-menu/overflow-menu-option.component.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
=> fix(overflow-menu-option): add `target` as a possible input for overflow-menu-option

src/input/label.component.ts
Closes IBM/carbon-components-angular#1628
**New**
**Changed**
**Removed**
=> fix(label): Fix regression showing ExpressionChangedAfterItHasBeenCheckedError and breaking unit tests.

carbon-angular-typedoc-theme/partials/analytics.hbs
=> chore(docs): add tracking to documentation site

src/search/search.component.html, src/search/search.component.ts, src/table/table.stories.ts
- icon is now non-interactive which simplifies complex aria requirements
- functionality of table search is smoother for both mouse and keyboard users
- table story now contains a `<section>` to resolve some story a11y issues
Closes IBM/carbon-components-angular#1600
=> fix(search): correct implementation for better accessibility

src/number-input/number.component.ts, src/number-input/number.stories.ts
=> feat(Number): add step and precision input

src/combobox/combobox.component.ts
Closes IBM/carbon-components-angular#1590
Moves around and cleans up all the roles and aria attrs in the component. I'm honestly not sure how we let it get this bad 😱
=> fix(combobox): improve accessibility for combobox

src/table/head/table-head.component.ts, src/table/table.stories.ts
Fixes https://github.com/IBM/carbon-components-angular/issues/1617
As per:
https://webaim.org/techniques/tables/data
https://webaim.org/techniques/tables/
https://www.w3.org/WAI/WCAG21/Techniques/html/H43
=> fix(accessibility): fix accessibility error for data table with no data

.github/workflows/codeql.yml
Borrowed from the AI Apps PAL - https://github.com/carbon-design-system/carbon-addons-iot-react/pull/1800
General CodeQL info: https://securitylab.github.com/tools/codeql
More info on the Action: https://github.com/github/codeql-action
=> chore: add CodeQL action to check for security issues

src/dropdown/dropdown.component.ts
=> Add label for to ibm-dropdown

src/table/body/table-row.component.ts, src/table/table-item.class.ts
Closes IBM/carbon-components-angular#1630
=> fix(table): Add title attr to table data cells

src/file-uploader/file-uploader.component.ts
Closes IBM/carbon-components-angular#1657
**New**
Added keyboard support to the drag and drop box
* to get focused by pressing the Tab key
* to show the file browser dialog on pressing the Space or Enter keys while focused
=> fix(file-uploader): Add keyboard support for the drag and drop box

src/tiles/expandable-tile.component.ts
Modify title attribute properly otherwise not title attribute gets applied
=> fix(accessibility): fix title not appearing

src/tabs/tab-headers.component.ts, src/tabs/tab.component.ts, src/tabs/tabs.stories.ts
=> feat(tabs): add title attribute to Tab

src/select/select.component.ts, src/select/select.stories.ts
=> feat(select): add ariaLabel input

src/combobox/combobox.component.ts
=> feat(combobox): add ControlValueAccessor method to programmatically disable combobox

src/table/table.component.ts
=> fix the table set focus issue

src/combobox/combobox.component.ts
=> fix(combobox): show clear button for multi select

src/patterns/forms/multi-step-form.stories.ts
Addresses #863 `Example forms`
=> docs: add multi-step-form pattern story

gulpfile.js
=> chore(readme): add readme to dist (and npmjs)

src/datepicker-input/datepicker-input.component.ts
=> feat(datepicker): hide icon for simple date picker

src/table/table.stories.ts
=> chore(table): fix story accessibility

package-lock.json, src/table/stories/app-no-data.component.ts, src/table/stories/app-table.component.ts, src/table/table.component.ts, typedoc.json
=> feat(table): add default simple table sort

src/content-switcher/content-switcher.component.ts, src/content-switcher/content-switcher.stories.ts
Adding light variant to content switcher
=> Add Content switcher light variant

src/search/search.component.html, src/search/search.component.ts
=> fix(search): added aria-label

package-lock.json, package.json, src/pagination/pagination.component.ts, src/pagination/pagination.module.ts
=> feat(pagination): Update to latest styles

.github/ISSUE_TEMPLATE.md
=> chore: add link for issue template

src/toggle/toggle.component.ts, src/toggle/toggle.stories.ts
=> feat(Toggle): add ControlValueAccessor method for disable

src/checkbox/checkbox.component.ts, src/checkbox/checkbox.stories.ts
=> feat(checkbox): add ControlValueAccessor method for disable

src/table/stories/app-custom-table.component.ts
=> fix(documentation): utilize ariaSortLabel for custom table header example

src/datepicker/datepicker.component.ts
=> feat(datepicker): add a way to include attributes to flatpickr's calendar

src/datepicker/datepicker.component.ts
Ports over the changes from #1759 to v3 since #1743 uses version 3
=> feat(datepicker): add a way to include attributes to flatpickr's calendar - v3

src/combobox/combobox.component.ts
Closes #1560
Ports over changes from #1641 to v3
=> fix(combobox): improve accessibility for combobox - v3

src/datepicker/datepicker.component.ts
=> feat(datepicker): Add keyboard navigation

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
=> feat(datepicker): add ControlValueAccessor method for disable

src/dialog/overflow-menu/overflow-menu-option.component.ts, src/dialog/overflow-menu/overflow-menu.stories.ts
Closes IBM/carbon-components-angular#1791
Fixes a few things I noticed were missing when working on the Cards implementation. Nothing blocking https://github.com/carbon-design-system/carbon-addons-iot-react/pull/2197, mainly just things to make the stories nicer.
=> fix(overflow-menu): add dividers, innerClass, and fix HostBinding

src/datepicker/datepicker.component.ts
=> fix(datepicker): fix tab sequence

src/checkbox/checkbox.component.ts
=> fix(checkbox): explicitly check if inputCheckbox exists before setting indeterminate

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/dropdown/dropdown.stories.ts
=> feat(combobox): Add auto dropUp detection

src/table/head/table-head.component.ts
=> fix(table): improve accessibility for table with no data

src/table/table.component.ts
=> fix(table): add guard for focusElementList

src/table/head/table-head-cell.component.ts, src/table/stories/app-table.component.ts, src/table/table-header-item.class.ts
=> feat(table): add title attribute to TableHeaderItem

package-lock.json, package.json, src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
=> feat(combobox): update html structure and classes

README.md, src/checkbox/checkbox.stories.ts, src/code-snippet/code-snippet.stories.ts, src/combobox/combobox.stories.ts, src/datepicker/datepicker.stories.ts, src/dropdown/dropdown.stories.ts, src/file-uploader/file-uploader.stories.ts, src/icon/icon.stories.ts, src/index.stories.ts, src/inline-loading/inline-loading.stories.ts, src/modal/modal.stories.ts, src/notification/notification.stories.ts, src/pagination/pagination-nav.stories.ts, src/pagination/pagination.stories.ts, src/patterns/dialogs/modal-with-table.stories.ts, src/patterns/filtering/multi-selection.stories.ts, src/patterns/filtering/multiple-categories.stories.ts, src/patterns/filtering/single-selection.stories.ts, src/patterns/forms/multi-step-form.stories.ts, src/patterns/loading/large-loading.stories.ts, src/patterns/loading/progressive-loading.stories.ts, src/progress-indicator/progress-indicator.stories.ts, src/radio/radio.stories.ts, src/select/select.stories.ts, src/table/table.stories.ts, src/toggle/toggle.stories.ts
=> chore: update README with support notices, add demo component notices to all app-* components

.storybook/webpack.config.js, package-lock.json, package.json, src/button/button-set.component.ts, src/button/button.directive.ts, src/button/button.module.ts, src/button/button.stories.ts, src/button/button.types.ts, src/button/index.ts, src/checkbox/checkbox.component.spec.ts, src/combobox/combobox.component.spec.ts, src/datepicker/datepicker.component.ts, src/dropdown/list/dropdown-list.component.ts, src/forms/index.ts, src/icon/icon.module.ts, src/number-input/number.component.spec.ts, src/number-input/number.component.ts, src/table/body/table-body.component.ts, src/table/body/table-expanded-row.component.ts, src/table/table.component.spec.ts
closes #1838 
closes #1824 
closes #1841 
closes #1747
Each issue is more or less contained in it's own commit, to help with reviewing. No huge changes, just a few little adjustments. This also updates our webpack config to use dart sass (and updates sass-loader and node-sass to not error on macOS 11)
=> A few small fixes

src/combobox/combobox.component.ts
Closes #1879 
This addresses the first issue in #1879. The second issue seems to have been addressed in #1819.
=> fix(combobox): remove aria-disabled attribute

src/modal/alert-modal.component.ts, src/modal/alert-modal.interface.ts, src/modal/modal-header.component.ts, src/modal/modal.service.ts, src/modal/modal.stories.ts
=> feat(modal): add option to hide header close button

.github/CONTRIBUTING.md, README.md
* Added IBMer specific contribution instructions in both readme and contribution.md
=> Add IBMer specific contribution instructions

src/dropdown/dropdown.component.ts
Closes IBM/carbon-components-angular#1900
**New**
**Changed**
**Removed**
=> wrap svg with styled span

src/placeholder/placeholder.service.ts
Closes IBM/carbon-components-angular#1928
=> fix(placeholder-service): Fix an ASSERTION ERROR in Angular 13

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes IBM/carbon-components-angular#1943
Fixed combobox setting reactive form dirty after value being set by the form
**Changed**
* Combobox no longer set reactive form control dirty after form's `setValue()`
=> fix(Combobox): fix reactive form being dirty after setting value

src/index.ts, src/layer/index.ts, src/layer/layer.directive.ts, src/layer/layer.module.ts, src/layer/layer.spec.ts, src/layer/layer.types.ts, src/theme/index.ts, src/theme/package.json, src/theme/theme.directive.ts, src/theme/theme.module.ts, src/theme/theme.spec.ts, src/theme/theme.stories.ts, src/tiles/tile.component.ts, src/tiles/tiles.stories.ts, src/timepicker/timepicker.component.ts, src/timepicker/timepicker.stories.ts
- Adds layer & theme components
- Update specific demos that now support layering to change theme
=> Implement layer & theme components

src/code-snippet/code-snippet.component.ts
Closes IBM/carbon-components-angular https://github.com/IBM/carbon-components-angular/issues/2208
=> fix: theme to be avaliable for all types of code-snippet

package-lock.json, package.json, src/tag/tag.component.ts, src/tag/tag.stories.ts
* Adds high-contrast and outline tag types
* Adds option to create small (size) tags
=> feat: add new tag types and size options

src/combobox/combobox.component.ts, src/dropdown/abstract-dropdown-view.class.ts, src/dropdown/list/dropdown-list.component.ts
Closes #2276
* Dropdown list now has an id attribute
* Combobox references dropdown list id attribute when open
* Removes redundant aria-haspopup attribute (View line 111 & 113)
=> fix: correct aria-haspopup value & add aria-controls attribute

.github/workflows/dco.yml
* Updates PAT to use Carbon-bot PAT
=> ci: Update to Carbon-bot PAT

.github/workflows/publish.yml, CODEOWNERS, package.json, scripts/deploy.sh
* Updates repo URL to the new URL (Which will also update url on NPM)
* Migrate from travis to github actions
`GITHUB_TOKEN` is generated every new JOB.
=> ci: Migrate from travis to github actions

.github/workflows/check-build.yml
* Runs build checks in next branch
=> chore: Run build check in next

src/file-uploader/file-item.interface.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file-uploader.stories.ts, src/file-uploader/file.component.ts, src/file-uploader/stories/drag-drop.component.ts, src/file-uploader/stories/uploader-form.component.ts, src/file-uploader/stories/uploader-reactive-form.component.ts, src/file-uploader/stories/uploader.component.ts
* Updates file item template for when `invalid`
* Added new size options (sm, md, lg) for file items
* Updated the stories & examples 
* Updated button size options to v11 (sm, md, lg).
=> feat: Update file item invalid template & add file item size

src/content-switcher/content-switcher.component.ts, src/content-switcher/content-switcher.stories.ts
Closes IBM/carbon-components-angular#2322
Add switcher size
=> feat: Add switcher size

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, .storybook/theme.js, README.md, package.json, src/package.json, src/slider/slider.component.ts
- Updates any instances of the old CCA repo URL to the new one (in carbon-design-system org)
=> chore: Update CCA repo link

src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts, src/modal/modal.component.ts
**New**
* On modal open, scrolling outside modal content will be disabled.
**Changed**
* Removed visibility subscription for better performance & to allow flatpickr to remain open when scrolling & in modals
=> fix(datepicker): Allow 'altInput' flatpickr option to be set to true

src/modal/modal.component.ts, src/modal/modal.stories.ts
Signed-off-by: Felipe Paluco <fepaluco@gmail.com>
Closes carbon-design-system/carbon-components-angular#2293
**New**
* Adds missing 'md' size for ibm-modal component
=> feat: Add missing 'md' size

src/icon/icon.service.ts
=> chore: Fix icons package typo

src/table/table.component.spec.ts, src/table/table.directive.ts, src/table/table.stories.ts, src/table/table.types.ts
* Corrects sizing option from small, short, medium & large to extra small, small, medium, large, extra-large
* Adds appropriate class based on size passed
=> fix: Update table sizes

src/timepicker-select/timepicker-select.component.ts, src/timepicker/timepicker.component.spec.ts, src/timepicker/timepicker.component.ts, src/timepicker/timepicker.stories.ts
* Add ariaLabel Input property to time picker select
* Add size option to time picker
* Allow users to override max length
* Add option to hide label
=> feat: Add missing time picker attributes

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
closes #2294 
* Adds helper text input property to date picker ( & range date picker).
=> feat: Add helper text attribute to datepicker

src/combobox/combobox.component.spec.ts, src/combobox/combobox.component.ts, src/dropdown/dropdown.component.ts, src/dropdown/list/dropdown-list.component.ts
- removed setTimeout from updateList method inside the dropdown list component which was delaying the execution of the closeDropdown method inside the combo box component until after the openDropdown method was called
- updated combo box component to filter dropdown list items by the current search string when new items are passed into the combo box component
- migrated tick call on the application reference from the dropdown component into the dropdown list component to trigger change detection when a dropdown list item is selected rather than waiting until the dropdown receives the new selection event
Closes carbon-design-system/carbon-components-angular#2426
=> fix(ibm-combo-box): show list of new items that match current search

integration/ng8/package-lock.json, integration/ng8/package.json
Reverts carbon-design-system/carbon-components-angular#2442
=> Revert "chore(deps): bump http-cache-semantics and @angular/cli in /integration/ng8"

src/tiles/clickable-tile.component.ts, src/tiles/expandable-tile.component.ts, src/tiles/selection-tile.component.ts, src/tiles/tiles.stories.ts
Closes https://github.com/carbon-design-system/carbon-components-angular/issues/1999
=> feat: Add theme inputs

src/tiles/clickable-tile.component.ts, src/tiles/expandable-tile.component.ts, src/tiles/selection-tile.component.ts, src/tiles/tiles.stories.ts
Signed-off-by: Moiz Masud <moizkhan_007@hotmail.com>
closes https://github.com/carbon-design-system/carbon-components-angular/issues/2453
=> feat: Add disable property to tiles

src/table/table.component.ts
Signed-off-by: Ravi Kumar [rkkp1023@gmail.com](mailto:rkkp1023@gmail.com)
Closes : https://github.com/carbon-design-system/carbon-components-angular/issues/2237
After this Pr merge You will notice these changes :
-> when you click on checkbox in table you will see outline (Accessibility)
=> fix(table): accessibility fix on checkbox

src/accordion/accordion.stories.ts, src/breadcrumb/breadcrumb.stories.ts, src/button/button.stories.ts, src/checkbox/checkbox.stories.ts, src/code-snippet/code-snippet.stories.ts, src/content-switcher/content-switcher.stories.ts, src/dropdown/dropdown.stories.ts, src/grid/grid.stories.ts, src/inline-loading/inline-loading.stories.ts, src/link/link.stories.ts, src/loading/loading.stories.ts, src/progress-indicator/progress-indicator.stories.ts, src/search/search.stories.ts, src/tag/tag.stories.ts, src/toggle/toggle.stories.ts
Closes https://github.com/IBM/carbon-ui-builder/issues/240
=> chore: Updated links to UI builder

src/slider/slider.component.ts
Closes carbon-design-system/carbon-components-angular#2444
Running change detection manually for the current component.
* Recheck view on view initialization
=> fix: NG0100 error when slider is used in template

src/icon/icon.module.ts, src/progress-indicator/progress-indicator.component.ts
Closes carbon-design-system/carbon-components-angular#2479
**Changed**
Before: 
After: Update icons to the [Carbon v10 Design](https://v10.carbondesignsystem.com/components/progress-indicator/usage/)
Before:
After: Fix doubled icons for the "error" state
=> Issue 2479: Progress Indicator: Design is different from the Carbon Components

src/context-menu/context-menu.component.ts
**Changed**
* Add deprecation notice to `root` input property. This will be removed in v5 as this property does not need to be disclosed to public
=> chore: Add root deprecation notice

src/table/head/table-head-cell.component.ts
Closes carbon-design-system/carbon-components-angular#2503
updated class name for correct sorting icon in table head cell
**New**
NA
**Changed**
class name for sort icon in tabel head cell
**Removed**
NA
=> fix: sorting icon for table head cell

src/number-input/number.component.ts, src/number-input/number.stories.ts
Closes carbon-design-system/carbon-components-angular#2510
added placeholder for ibm number
**New**
added placeholder for ibm number
**Changed**
NA
**Removed**
NA
=> feat: add placeholder for ibm number

src/progress-indicator/progress-indicator.component.ts, src/progress-indicator/progress-indicator.stories.ts
Closes carbon-design-system/carbon-components-angular#2513
**Before**
**Changed**
Vertical progress indicator:
Horizontal progress indicator:
=> issue-2513: Progress Indicator: fixed optionalText styling to make it consistent with react carbon component

src/combobox/combobox.component.ts
Closes carbon-design-system/carbon-components-angular#2558
**Update**
* Prevents new DOM element from being added on search string change
=> fix: Create only 1 listbox element per combobox

src/ui-shell/sidenav/sidenav-item.component.ts, src/ui-shell/sidenav/sidenav-menu.component.ts, src/ui-shell/ui-shell.stories.ts
Closes carbon-design-system/carbon-components-angular#1889
Before
After
Before
After
=> Fix sidenav active state not showing and icon placement

src/tabs/tab-headers.component.ts, src/tabs/tab.component.ts
* Correct left button title
* Use static counter for id
=> fix: Correct left button title

src/icon/icon.directive.ts
**Changed**
* Render icon after view has initialized & icon has registered instead of on Change
=> fix: Render icon after view init on initial change

src/table/head/table-head-checkbox.component.ts
**Removed**
* Size input property as it is no longer used in the template or code
=> fix: Remove size input prop

package-lock.json, package.json, src/toggle/toggle.component.ts, src/toggle/toggle.stories.ts
**New**
* Re-add skeleton state to toggle component
=> feat: Add skeleton state

src/content-switcher/content-switcher.component.ts
**Changed**
* Query select by new & old selector
=> fix: Query select by new & old selector

src/table/stories/app-custom-table.component.ts
=> docs: get template after view initializes

src/icon/icon.directive.ts, src/input/label.component.ts, src/input/text-input-label.component.ts
**Changed**
* Check if cdsIcon has a truthy value in ngOnChange
* Use cdsIcon directive instead of `ibmIcon` in label
=> fix: check if cdsIcon value is truthy

src/input/text-input-label.component.ts, src/input/textarea-label.component.ts
=> chore: lint

src/accordion/accordion.component.ts, src/button/button.directive.ts, src/input/input.directive.ts, src/tag/tag-filter.component.ts, src/tag/tag.component.ts
**New**
* Add new size classes
=> fix: Update size css classes to new layout size classes

src/table/head/table-head-cell.component.ts, src/table/table-header-item.class.ts, src/table/table-model.class.spec.ts, src/table/table-model.class.ts, src/table/table.component.ts
**New**
* Users can reset sort on 3rd click on same header item
=> feat: Add initial sort state 

src/number-input/number.component.ts
Closes carbon-design-system/carbon-components-angular#2597
**Changed**
* Bind value using `attribute binding` to prevent value from being deleted
=> fix: Set value for attribute directly using attribute binding

README.md
* Updates angular support matrix
=> docs: Update angular version support matrix

README.md, integration/ng12/package-lock.json, integration/ng12/package.json, src/checkbox/checkbox.component.ts
Closes #2623
**Changed**
* Set ariaLabel attribute to be undefined by default instead of an empty string.
=> Checkbox aria label

.github/workflows/check-build.yml, .github/workflows/codeql.yml, .github/workflows/publish.yml, .github/workflows/test.yml, package.json
**Changed**
* Updates github actions workflow for CCA v4 to use new `v10` branch name
=> chore: Update actions to use v10 branch

package.json
Brings in all of the changes from next branch AFTER breaking change 5.13.2@next
=> feat: Publish latest changes

src/combobox/combobox.component.ts
Closes carbon-design-system/carbon-components-angular#2667
**Changed**
* Emit selected event for multiselect combobox
=> fix: Emit selected event for multiselect

src/pagination/pagination.component.ts
Closes carbon-design-system/carbon-components-angular#https://github.com/carbon-design-system/carbon-components-angular/issues/2664
FYI: Already submitted PR for the current version: https://github.com/carbon-design-system/carbon-components-angular/pull/2677
=> fix: make pagination text consist on resize

src/progress-indicator/progress-indicator.stories.ts
Closes carbon-design-system/carbon-components-angular#2691
A typo in orientation options in progress indicator storybook was corrected.
**Changed**
A typo in orientation options in progress indicator storybook was corrected.
=> docs: orientation options in progress indicator storybook

src/context-menu/context-menu.component.ts
Closes #2749 
updated the context menu module import
**Changed**
* Updated the context menu module import in the story book.
=> docs: update context menu module import

package-lock.json, package.json, src/accordion/accordion-item.component.ts
Closes carbon-design-system/carbon-components-angular#2757
**Changed**
* fix: remove accordion item flickering
* fix: update peer dependency to require @carbon/style@1.44.0
=> fix: accordion item flickering

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.stories.ts
Closes carbon-design-system/carbon-components-angular#2738
Closes carbon-design-system/carbon-components-angular#2762
**Changed**
* Wrap date picker input and icon in span
* Pass unique id to range date picker in storybook
=> fix: align datepicker icon relative to input

src/code-snippet/code-snippet.component.ts
Closes #2782 
Added optional chaining to get rid of the null check error in the console.
=> fix : null check console error

.storybook/manager-head.html
ref: https://github.com/carbon-design-system/carbon-components-angular/issues/2774
Adds privacy policy footer to storybook
=> docs: Add privacy policy footer

.github/workflows/check-build.yml, .github/workflows/publish.yml
ref: https://github.com/carbon-design-system/carbon-components-angular/pull/2798
Use node 18 for ci environment
**Changed**
* Using node 18 for deploy enviornment
=> ci: use node 18 for publish enviornment

src/ui-shell/header/hamburger.component.ts
Allow title text to be overridden using input prop for hamburger component.
**New**
* Add input property to hamburger component to override active/inactive title text
=> feat: allow title text to be overridden using input prop

src/ui-shell/sidenav/side-nav.component.spec.ts
=> chore: lint fix

src/popover/popover.directive.ts
**Changed**
* reverting default value for high contrast changed with floating-ui fix
=> fix: revert high contrast to false by default for popover

src/dropdown/list/dropdown-list.component.ts
Closes #2830 
Resolves the error, on reading nativeElement when all the list items are disabled.
For details info on the error, please refer to the issue #2830
=> fix: resolve cannot read property of undefined when all list items are disabled

src/tooltip/tooltip.component.ts
=> chore: add semicolon

src/button/icon-button.stories.ts
**Changed**
* Fixes story errors
=> chore: correct event function typo

telemetry.yml
Instrument with IBM Telemetry [JS scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)
**New**
- Add [JS scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) config to `telemetry.yml`
=> feat: add telemetry JS Scope

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts
Accessibility improvement to combobox and dropdown.
**New**
* Can hide label for dropdown and combobox
**Changed**
* Combobox label is now read by screen reader
=> fix: allow labels to be read for combobox and hide labels but keep them accessible to screen reader

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/stories/app-reactive-forms.component.ts, src/input/password.spec.ts
**New**
* Allow labels to be hidden but accessible by screen readers for combobox and dropdown
=> feat: allow labels to be hidden but accessible by screen readers

src/treeview/tree-node.component.ts, src/treeview/tree-node.types.ts, src/treeview/treeview.component.ts
Closes carbon-design-system/carbon-components-angular#2913
**Changed**
* Allow users to pass template for treeview label + context
* Allow users to pass context for treeview node icon
=> fix: allow users to pass template for label

src/ui-shell/ui-shell.stories.ts
**Changed**
* Reference correct args and argTypes for UI-shell stories
=> docs: correct story args and argTypes

src/datepicker/datepicker.component.ts
Closes carbon-design-system/carbon-components-angular#2951
**Changed**
* Check if `skeleton` is `false` before trying to access property of View Child
=> fix: prevent access property of view child when skeleton is enabled

src/input/input.stories.ts, src/input/label.component.ts, src/input/text-input-label.component.ts
Closes #2901 
Added readonly state for the text input. Introduced new  boolean variable as an `@Input()` for the readonly state, updated the storybook as well that reflects the changes.
=> feat: Add readonly state

src/treeview/treeview.component.ts, src/treeview/treeview.service.ts
Closes carbon-design-system/carbon-components-angular#2963
Exposed TreeviewService as public variable in Treeview component and implemented `deselectNode` and `deselectAllNodes` to have the ability to programmatically select/deselect nodes
**New**
* TreeviewService now implementing deselection capabilities
**Changed**
* Treeview component publicly exposing their TreeviewService instance
=> feat: expose treeViewService and add deselection capability to it

src/patterns/forms/multi-step-form.stories.ts
Fix multi-step form story to use correct progress indicator steps.
=> chore: fix multi-step story

src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes carbon-design-system/carbon-components-angular#2894
=> feat: add readonly state for combobox

src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts
Closes carbon-design-system/carbon-components-angular#2896
=> feat: readonly state for dropdown

src/input/password-input-label.component.ts, src/input/password.stories.ts
Closes carbon-design-system/carbon-components-angular#2900
=> feat: readonly state for password input

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts, src/datepicker/datepicker.stories.ts
Closes carbon-design-system/carbon-components-angular#2895
=> feat: readonly state for date picker

src/select/select.component.ts, src/select/select.stories.ts
Closes carbon-design-system/carbon-components-angular#2899
=> feat: readonly state for select

src/slider/slider.component.ts, src/slider/slider.stories.ts
Closes carbon-design-system/carbon-components-angular#2898
=> feat: readonly state for slider

src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts
Closes carbon-design-system/carbon-components-angular#2983
=> fix: datepicker skeleton not showing up

src/input/password-input-label.component.ts, src/input/text-input-label.component.ts
Closes carbon-design-system/carbon-components-angular#2985
**Changed**
* Resolve NG0100 runtime error caused by initial readonly state
=> fix: resolve NG0100 runtime error caused by initial readonly state

package-lock.json, package.json, src/datepicker/datepicker.component.ts, src/ng-package.json, src/package.json, src/select/select.component.ts, src/treeview/tree-node.component.ts, src/treeview/tree-node.types.ts, src/treeview/treeview.component.ts
Resolves build issue for requiring lodash when shell component is being used
**Changed**
* Added lodash as a dependency to import `keys`.
=> fix: add lodash as a dependency

src/search/search.component.html, src/search/search.component.ts, src/search/search.stories.ts
Closes carbon-design-system/carbon-components-angular#2889
=> feat: fluid state for search

src/combobox/combobox.component.ts
changed id prefix in ComboBoxComponent to fix id conflicts with DropdownComponent
closes [#3022](https://github.com/carbon-design-system/carbon-components-angular/issues/3022)
=> fix combobox id assignement

src/select/select.component.ts, src/select/select.stories.ts
Closes carbon-design-system/carbon-components-angular#2890
=> feat: fluid state for select

src/breadcrumb/breadcrumb.component.spec.ts, src/breadcrumb/breadcrumb.component.ts, src/breadcrumb/breadcrumb.module.ts, src/dialog/dialog.module.ts, src/dialog/overflow-menu/overflow-menu.component.ts, src/i18n/en.ts
Closes carbon-design-system/carbon-components-angular#2726
=> fix: breadcrumb overflow menu icon alignment

src/progress-indicator/progress-indicator.component.ts
=> docs: fix import typo

src/number-input/number.component.spec.ts, src/number-input/number.component.ts, src/number-input/number.stories.ts
Notes:
- Added logic to `onIncrement` and `onDecrement` to constrain values within min and max bounds
- Updated tests to verify min/max constraints
- Conform with React implementation
Value | Step | Min | Max | Result before | Result after
-- | -- | -- | -- | -- | --
0 | 10 | 15 |   | 10 | 15
95 | 10 |   | 100 | 95 | 100
105 | 10 |   | 100 | 105 | 100
Value | Step | Min | Max | Result before | Result after
-- | -- | -- | -- | -- | --
20 | 2 |   | 15 | 18 | 15
6 | 2 | 5 |   | 6 | 5
10 | 2 | 15 |   | 10 | 15
https://github.com/user-attachments/assets/dc16654b-c70e-4071-ad19-e6f9de0efbb6
=> feat: enhance increment and decrement functionality number component

package.json
Release next branch versions with `rc` suffix
**New**
* Release next branch releases with `rc` suffix
=> ci: add a pre-release tag to next branch

src/icon/icon.directive.ts, src/link/index.ts, src/link/link-icon.directive.ts, src/link/link.module.ts, src/link/link.stories.ts
Create link directive to pair icon with link
**New**
* Create link directive to pair icon with link
**Changed**
* Assign `fill` attribute to icons specified in `@carbon/icons`
=> feat: create link directive to pair icon with link

src/tiles/clickable-tile-icon.directive.ts, src/tiles/clickable-tile.stories.ts, src/tiles/index.ts, src/tiles/tiles.module.ts
Add clickable tile Icon directive
**New**
* Directive to position icon in bottom right of a clickable tile
=> feat: Add clickable tile Icon directive

src/toggle/toggle.component.ts
Accessibility improvement for toggle when you don't want to pass in a label.
**New**
* Allow users to pass in aria-label for button
=> fix: allow users to pass in aria-label for toggle button

src/tag/index.ts, src/tag/tag-filter.component.spec.ts, src/tag/tag-filter.component.ts, src/tag/tag-icon.directive.ts, src/tag/tag-operational.component.ts, src/tag/tag-selectable.component.ts, src/tag/tag.component.ts, src/tag/tag.module.ts, src/tag/tag.stories.ts
Tag parity
**New**
* Add support for icons in tags
* Add `skeleton` state
* Created operational / selectable tag components
=> feat: introduce selectable & operational tags

README.md
Closes carbon-design-system/carbon-components-angular#3057
**Changed**
* doc: change codesandbox to stackblitz
=> doc: update codesandbox to stackblitz

package-lock.json, package.json, src/combobox/combobox.component.ts, src/combobox/combobox.stories.ts
Closes carbon-design-system/carbon-components-angular#2885
=> feat: fluid state for combobox

src/combobox/combobox.component.ts, src/content-switcher/content-switcher.component.ts, src/context-menu/context-menu-divider.component.ts, src/context-menu/context-menu-group.component.ts, src/context-menu/context-menu-item.component.ts, src/context-menu/context-menu.component.ts, src/datepicker-input/datepicker-input.component.ts, src/datepicker/datepicker.component.ts
Epic carbon-design-system/carbon-components-angular#3066
**Changed**
- Combobox
- Content switcher
- Context menu
- Date picker
=> feat: convert components to use OnPush change detection strategy

.github/workflows/codeql.yml, .github/workflows/publish.yml, .github/workflows/test.yml, .npmrc
**Changed**
* Bump GitHub actions to latest version
* Create npmrc file to enable publishing with provenance
=> feat: create npmrc file to enable publishing with provenance & bump github actions

src/code-snippet/code-snippet.component.ts, src/code-snippet/code-snippet.stories.ts
**Changed**
* Pass `autoAlign` property to `cds-icon-button`.
=> fix: pass autoAlign property to icon button

src/combobox/combobox.component.spec.ts, src/dropdown/dropdown.component.spec.ts, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.stories.ts, src/dropdown/list/dropdown-list.component.ts, src/file-uploader/file-uploader.component.ts, src/file-uploader/file.component.ts, src/inline-loading/inline-loading.component.ts, src/inline-loading/stories/inline.component.ts
Update components to use On Push, part of  [issue-3066](https://github.com/carbon-design-system/carbon-components-angular/issues/3066)
**Changed**
Dropdown + fix unit tests
File Uploader
Inline loading
=> feat: convert components to use OnPush change detection strategy 2
